/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "/ day": "/ 天",
    "'I am so hungry, Thanks Mom!'": "",
    "*🔎All Cards": "*🔎全部卡片",
    "Broken Leg": "断腿",
    "Buy a Car": "买辆车",
    "💰Bank Account:": "💰银行账户:",
    "-Infuence-Za Fashion 19-": "-影响-Za时尚19-",
    "'you are worthless, worse than worthless' - the rich to the poor": "“你一文不值，比一文不值还要糟糕”——富人对穷人",
    "$8.9 million a year out of her!": "她一年890万美元！",
    "1 liberty bell, 3 liberty bells": "1 个自由钟、3 个自由钟",
    "10 Million Subscribers on YouTube": "YouTube 上有 1000 万订阅者",
    "A Big Night Out": "一个美好的夜晚",
    "A Brush with Death": "与死亡擦肩而过",
    "a few years in the blink of an eye": "转眼几年",
    "a massive group of dollar bills": "一大堆美元钞票",
    "A Nice Necklace": "一条漂亮的项链",
    "A Real Saver": "真正的节省者",
    "A REALLY Good Day!": "真是美好的一天！",
    "about time...": "关于时间...",
    "Achieve a Life Long Goal": "实现终生目标",
    "after the trial, throw away the key": "试用后，扔掉钥匙",
    "Alaskan Adventure": "阿拉斯加探险",
    "all night long, star of the floor": "整夜，地板之星",
    "all that planning paid off": "所有的计划都得到了回报",
    "all you can drink": "无限畅饮",
    "always on the lookout": "始终保持警惕",
    "am I successful enough yet?": "我还足够成功吗？",
    "Amen!": "阿门！",
    "an ayahuasca retreat!": "死藤水静修！",
    "and terrible choices..": "和可怕的选择..",
    "and these are my all natural organic gluten free picture frames": "这些是我的全天然有机无麸质相框",
    "and this next song is about...": "下一首歌曲是关于...",
    "Annual Bonus = $0": "年度奖金 = $0",
    "Annual Christmas Heist": "一年一度的圣诞抢劫",
    "Annual Season Pass - The Ski Hill": "年度季票 - 滑雪场",
    "another world down here": "这里是另一个世界",
    "Antarctic Expedition": "南极探险",
    "anyone looking?": "有人在找吗？",
    "are you kidding me Dina?": "迪娜，你在开玩笑吗？",
    "atop her, my statue, golden throne, diamond upon my crown": "在她的顶上，我的雕像，金色的王座，我的王冠上有钻石",
    "Attract a Lover": "吸引情人",
    "Australia, under my thumb": "澳大利亚，在我的掌控之中",
    "Bad Decisions": "错误的决定",
    "bare knuckle": "裸关节",
    "Bathe in a Million in Cash, then Burn it": "沐浴一百万现金，然后烧掉它",
    "battered old thing": "破旧的东西",
    "be like me": "和我一样",
    "Beat Cookie Clicker": "击败饼干唱首歌",
    "Become a Crazy Cat Person": "成为一个疯狂的猫人",
    "Become a Famous Magician": "成为著名魔术师",
    "Become an Influencer and Film Dance Clips in Public": "成为有影响力的人并在公共场合拍摄舞蹈片段",
    "Become Mayor of Timbuktu": "成为廷巴克图市长",
    "Become Spiritual": "变得有灵性",
    "Become Vegan": "成为素食主义者",
    "begin production": "开始生产",
    "Begin Work.. Secret Work": "开始工作..秘密工作",
    "Bet It All On Red": "全力押注红色",
    "better wash before you wear": "穿之前最好先洗一下",
    "Betting on Underground Cage Fights": "投注地下笼斗",
    "Big Loan": "大额贷款",
    "Birthday Gift": "生日礼物",
    "Blackmail the POTUS": "勒索美国总统",
    "BOGO baby!": "波戈宝贝！",
    "boom": "繁荣",
    "boost you productivity rates": "提高您的生产率",
    "bow to me, you dumb peasants": "向我鞠躬，你们这些愚蠢的农民",
    "bow to my greatness": "向我的伟大低头",
    "brand new": "全新",
    "bravo on being so kind!": "太善良了！",
    "Breakfast in Bed": "在床上吃早餐",
    "Bribe a Cop": "贿赂警察",
    "Bribe the Royal Family": "贿赂皇室",
    "bring your snorkel": "带上你的通气管",
    "Build a 20,000 Car Parkade for Your Home": "为您的家建造一个可容纳 20,000 个停车位的停车场",
    "Build a Crypto Currency Farm": "建立一个加密货币农场",
    "Build a Giant Bathtub": "建造一个巨型浴缸",
    "Build a Mountain from Diamonds": "用钻石建造一座山",
    "Build a Personal Hockey Rink": "建造个人曲棍球场",
    "Build an Underwater Hotel": "建造水下酒店",
    "but I thought..": "但我想..",
    "but never tell": "但永远不要告诉",
    "Buy 1000 Hamsters": "购买 1000 只仓鼠",
    "Buy a Bike": "买一辆自行车",
    "Buy a Cannabis Shop": "购买大麻店",
    "Buy a Computer": "购买电脑",
    "Buy a Dividend Fund": "购买股息基金",
    "Buy a House in Panama": "在巴拿马买房子",
    "Buy a Kitten": "买一只小猫",
    "Buy a Manhattan Parking Spot": "购买曼哈顿停车位",
    "Buy a Mansion In the Boonies": "在布尼区购买豪宅",
    "Buy a Mansion on a Lake": "购买湖边豪宅",
    "Buy a Painting by a Famous Artist": "购买著名艺术家的画作",
    "Buy a Patagonia Jacket": "买一件巴塔哥尼亚夹克",
    "Buy a Private Jet": "购买私人飞机",
    "Buy a Race Car": "买一辆赛车",
    "Buy a Really Nice House for Mom and Dad": "为爸爸妈妈买一栋非常漂亮的房子",
    "Buy a Rental Property": "购买出租物业",
    "Buy a Super-Computer Laptop, for Productivity and gaming": "购买超级电脑笔记本电脑，提高工作效率和玩游戏",
    "Buy a Surfboard": "买一块冲浪板",
    "Buy a Tiny Downtown One Room Condo": "购买一套小型市中心单间公寓",
    "Buy a tiny Yacht": "买一艘小型游艇",
    "Buy a Very Nice Wake Surf Boat": "购买一艘非常好的尾波冲浪船",
    "Buy a Vineyard in France": "在法国购买葡萄园",
    "Buy All Your Friends Cars": "购买你所有朋友的汽车",
    "Buy an Amateur Soccer Team": "购买一支业余足球队",
    "Buy an Investment Bank": "购买投资银行",
    "Buy an Ultra Fancy Car": "购买一辆超豪华的汽车",
    "Buy Extremely Fancy Shoes": "买非常漂亮的鞋子",
    "Buy Friends So You Can Scam them Later": "购买好友，以便以后可以诈骗他们",
    "Buy Graff Diamonds Hallucination Watch": "购买格拉夫钻石幻觉腕表",
    "Buy Long Term Bonds": "购买长期债券",
    "Buy Mount Everest, Make It Yours": "购买珠穆朗玛峰，让它成为你的",
    "Buy New Friends": "购买新朋友",
    "Buy Starter House": "购买入门房",
    "Buy Success": "购买成功",
    "Can I 'borrow' a Hundred G, G?": "我可以‘借’一百G吗？",
    "Can I 'borrow' an Easy Milly, Billy?": "我可以“借”一个简单的米莉吗，比利？",
    "can't help myself": "情不自禁",
    "Cannot Afford": "不能负担",
    "Capture Rare Footage": "捕捉稀有镜头",
    "Cash in on Race Privilege": "兑现比赛特权",
    "catch some waves": "抓住一些波浪",
    "Catch that Pesky Road Runner": "抓住那个讨厌的公路跑者",
    "cats only, all cats": "仅猫，所有猫",
    "cause I don't want to be embarrassed by them": "因为我不想让他们感到尴尬",
    "Cheat on Your Spouse with a Model": "用模特欺骗你的配偶",
    "chicken fried rice?": "鸡肉炒饭？",
    "Click on cards to purchase. Cards affect the rate that you generate $ and happy": "点击卡片即可购买。 卡会影响你产生美元和快乐的比率",
    "Climb a Mountain": "爬山",
    "Collect Child Support Baby!": "收集儿童抚养费宝贝！",
    "Collect Rare, Vintage Comics": "收集稀有的复古漫画",
    "College Diploma": "大学文凭",
    "Come Out of the Closet": "出柜",
    "coming to you from Earth": "从地球来到你身边",
    "Conduct an Annual Blood Ritual": "进行一年一度的献血仪式",
    "Construct a Bowling Alley": "建造一个保龄球馆",
    "Construct the Tallest Building in the World!": "建造世界上最高的建筑！",
    "Control Wall Street": "控制华尔街",
    "convenience, elegance": "便利、优雅",
    "Corner the Paper Route Market": "垄断纸路市场",
    "cost of doing business": "做生意的成本",
    "Cost of living: $": "生活费用：$",
    "coupon hunter": "优惠券猎人",
    "Crack Addiction": "破解成瘾",
    "create a human-level AI": "创造人类水平的人工智能",
    "Create a Religion of You": "创造你的宗教",
    "Create an Online Fashion Boutique": "创建在线时装精品店",
    "Creep with the Girl Next Door": "与邻家女孩一起爬行",
    "customers first": "客户至上",
    "cute lil guys": "可爱的小家伙们",
    "days /": "天 /",
    "Debts Forgiven": "债务被免除",
    "deserved it but it was worth it": "这是应得的，但这是值得的",
    "Design a Rocket Ship": "设计一艘火箭飞船",
    "Design and Sell Print-on-Demand T-shirts": "设计和销售按需印刷 T 恤",
    "Design Pyramid Scheme, Deploy Pyramid Scheme": "设计金字塔计划、部署金字塔计划",
    "desperate times": "绝望的时刻",
    "Develop Mood Enhancing Pills": "开发情绪增强药",
    "didn't read the small print": "没有阅读小字",
    "Dig in the $#!%, Literally": "从字面上看，挖掘 $#!%",
    "Dirty Money, But Good Money": "脏钱，但好钱",
    "Discover Atlantis": "探索亚特兰蒂斯",
    "Discover Life on Mars": "发现火星上的生命",
    "Discover the Next American Idol": "发现下一个美国偶像",
    "do not even look at me...": "连看都不看我一眼...",
    "Do Someones Dirty Work": "做一些肮脏的工作",
    "Don’t forget to pickup the poop": "别忘了捡起便便",
    "Donate your Liver": "捐献你的肝脏",
    "Drink Away Your Sorrows": "喝掉你的悲伤",
    "Drinking Habit": "饮酒习惯",
    "Earn a Favor from a Hot Shot Politician": "赢得热门政客的青睐",
    "Earn What Jeff Bezos Earns": "赚取杰夫·贝索斯的收入",
    "Earn your Masters": "获得硕士学位",
    "Eat a Banana": "吃一根香蕉",
    "End World Suffering": "结束世界苦难",
    "Enslave a Lost People": "奴役迷失的人民",
    "Enter a Beauty Contest and Lose": "参加选美比赛并输掉比赛",
    "Enter the World of Extreme Couponing": "进入极限优惠券的世界",
    "ew.. what are you?": "呃..你是什么？",
    "excuse me sir...": "对不起，先生...",
    "exfoliate the flesh": "去角质",
    "Expensive Date": "昂贵的约会",
    "Expensive Habits": "昂贵的习惯",
    "Experience Your Darkest Fantasy": "体验你最黑暗的幻想",
    "Extort the Competition": "勒索竞争",
    "Family Reunion": "家庭团聚",
    "fear me": "怕我",
    "Featuring Superman as the Weakest Man in the World": "超人是世界上最弱的人",
    "Fight for the UFC Heavyweight Title": "争夺UFC重量级冠军",
    "Fight to the Death and Win": "战斗至死并取得胜利",
    "fill it with super cars": "装满超级跑车",
    "fill it with yachts and bubbles": "用游艇和泡泡填满它",
    "finally free of the peasant scum": "终于摆脱了农民渣",
    "finally some money": "终于有钱了",
    "Financial Education": "理财教育",
    "Financial Goals": "财务目标",
    "Find a Message in a Bottle": "寻找瓶中信",
    "Find a Potato Chip in the Shape of Jesus": "找到耶稣形状的薯片",
    "Find a Tax Loophole": "寻找税务漏洞",
    "finding balance": "找到平衡",
    "Fire up the grill": "点燃烤架",
    "First Kiss": "初吻",
    "fly little birds! be free": "小鸟飞翔吧！ 是自由的",
    "Focus on Your Career": "专注于你的职业生涯",
    "follow your heart": "跟随你的心",
    "for hipsters only": "仅限潮人",
    "for money": "为了钱",
    "for tax purposes": "出于税收目的",
    "for the birthdays I deserve": "为了我应得的生日",
    "for the future": "为将来",
    "Form a Gambling Addiction": "养成赌博成瘾的习惯",
    "Form a Medical Cannabis Producer": "组建医用大麻生产商",
    "Form a Sovereign Country": "建立主权国家",
    "free drinks for friends": "为朋友提供免费饮料",
    "Free Your Harem": "解放你的后宫",
    "freedom": "自由",
    "fresh air": "新鲜空气",
    "fries with that?": "炸薯条吗？",
    "Full-Time Job": "全职工作",
    "fully 'legal'": "完全“合法”",
    "Fund a Private Moon Mission": "资助私人月球任务",
    "Fund a Rainforest Renewal Project": "资助雨林更新项目",
    "Fund Unethical Research Studies": "资助不道德的研究",
    "Gain Their Blind Trust": "获得他们的盲目信任",
    "get a bonus on the first day of every year": "每年第一天获得奖金",
    "Get a Driver's License": "获得驾驶执照",
    "Get a Lawn Mowing Job": "找到一份割草工作",
    "Get a Roofing Job": "找一份屋顶工作",
    "Get a second sexual organ": "获得第二性器官",
    "Get Arrested for Streaking Past McDonalds": "因裸奔麦当劳而被捕",
    "Get Away with Insurance Fraud": "远离保险欺诈",
    "Get Caught Checking Someone Out": "结账时被抓",
    "Get delivering!": "快去送货吧！",
    "Get Elected as Chairman of the Board": "当选为董事长",
    "Get Flexible": "变得灵活",
    "Get Mugged": "被打劫",
    "Get Punched in the Face": "被打脸",
    "Get Scammed": "被骗",
    "Get Sweet Revenge on Montezuma": "对蒙特祖玛进行甜蜜的复仇",
    "Get Two Hole in Ones in a Row": "连续两个洞",
    "Give your Child 25 Billion Dollars": "给你的孩子250亿美元",
    "Go Dancing": "去跳舞",
    "Go for Walks": "去散步",
    "Go Global Straight Up": "直接走向全球",
    "Go Hunting in Alaska and Nebraska": "去阿拉斯加和内布拉斯加州狩猎",
    "Go on Sky Diving Retreat": "继续跳伞静修",
    "Go out for a Stupidly Expensive Dinner": "出去吃一顿贵得离谱的晚餐",
    "Go to a Concert": "去听音乐会",
    "Go to Low Earth Orbit on a Virgin Galactic Space Plane": "乘坐维珍银河太空飞机前往近地轨道",
    "Go to the Spa": "去水疗中心",
    "Good Karma": "善业",
    "good kids": "好孩子",
    "Good Luck in the Markets": "祝市场好运",
    "got my shots!": "我的镜头得到了！",
    "gotta start somewhere": "必须从某个地方开始",
    "Graduate High School": "研究生高中",
    "grand opening discount": "开业折扣",
    "Gravel Kickers United": "碎石踢球者联队",
    "great food, every day": "美味的食物，每一天",
    "ha ha sucka": "哈哈 苏卡",
    "hamburger buns never looked so good": "汉堡包从未看起来如此美味",
    "Hang Glide Naked Over a Volcano": "赤裸悬挂在火山上滑翔",
    "happiness can buy money": "幸福可以买钱",
    "Happy 😄: 122.": "快乐😄：122。",
    "Happy Booster": "快乐助推器",
    "Hard Work Pays Off": "付出就有收获",
    "Have a Great Monument Built in Your Honor": "以您的名义建造一座伟大的纪念碑",
    "Have Beautiful Children": "拥有美丽的孩子",
    "have you beaten cookie clicker?": "你打败过饼干点击器吗？",
    "Help a Stranger": "帮助陌生人",
    "Help Save Starving Children": "帮助拯救饥饿的儿童",
    "helping others help themselves": "帮助别人帮助自己",
    "Hire a Maid": "聘请女佣",
    "Hire a Master Chef": "聘请一位主厨",
    "Hire Body Guards": "雇用保镖",
    "Hire the Best Therapist for Psychopath": "为精神病患者聘请最好的治疗师",
    "Hola!": "你好！",
    "Horde your Wealth": "聚集你的财富",
    "Host a Summer BBQ for all your Friends": "为您所有的朋友举办夏季烧烤",
    "hot tar": "热焦油",
    "hours passed": "几个小时过去了",
    "how can you lose?": "你怎么能输呢？",
    "how much are you thinking?": "你想多少？",
    "I am a bird now": "我现在是一只鸟",
    "I am a good person now": "我现在是一个好人了",
    "I am good for it": "我很擅长",
    "I AM SO H A P P Y !": "我太高兴了 ！",
    "I am the BIRD! am I?": "我是鸟！ 我是吗？",
    "I appreciate the work the devs do": "我很欣赏开发人员所做的工作",
    "I brought a gun to a knife fight": "我带着枪参加刀战",
    "I can not believe they bought it!": "我不敢相信他们买了它！",
    "I can't stop smiling": "我无法停止微笑",
    "I demand a return on my investment!": "我要求我的投资得到回报！",
    "I did it!": "我做到了！",
    "I don't do dirty work": "我不做肮脏的工作",
    "I don't even miss it": "我什至不想念它",
    "I don't know what you are talking about": "我不知道你在说什么",
    "I earned this": "我赚到了这个",
    "I feel better now": "我现在感觉好多了",
    "I felt a spark...": "我感觉到了火花...",
    "I guess I'll take it": "我想我会接受它",
    "I hate you all!": "我恨你们！",
    "I have conquered Everest": "我已经征服了珠穆朗玛峰",
    "I have no social life": "我没有社交生活",
    "I hope I don't regret this": "我希望我不会为此后悔",
    "I just had a feeling..": "我只是有一种感觉..",
    "I just know a guy in Office, soooo..": "我只认识办公室里的一个人，所以..",
    "I make wish now": "我现在许愿",
    "I missed jumping": "我错过了跳跃",
    "I need cash not smiles": "我需要现金而不是微笑",
    "I need the money": "我需要那些钱",
    "I only use my arms": "我只用我的手臂",
    "I pay you, you let me win": "我付钱给你，你让我赢",
    "I think I like myself now": "我想我喜欢现在的自己",
    "I was born with this": "我生来就有这个",
    "I was happy before, but now that we met I am SO HAPPY!": "以前我很高兴，但现在我们见面了，我很高兴！",
    "I will ruin you": "我会毁了你",
    "I'll do anything": "我会做任何事",
    "I'll give you bacon": "我给你培根",
    "I'll give you whatever you want!": "你想要什么我都给你！",
    "I'll pay this time, again guys": "这次我会付钱的，伙计们",
    "I'll pay you back...": "我会还给你的...",
    "I'm just that important": "我就是这么重要",
    "I'm Rich and I know it": "我很富有，我知道这一点",
    "I'm so embarrassed": "我好尴尬",
    "I'm so weak now I feel strong": "我现在很虚弱，我感觉自己很坚强",
    "I'm talkin full splits, both ways": "我正在谈论完全分裂，双向",
    "I'm telling you! I saw what I saw!": "我告诉你！ 我看到了我所看到的！",
    "Idle Trillionaire": "闲置亿万富翁",
    "If only...": "要是...",
    "if they pay, I sell": "如果他们付钱，我就卖",
    "if you can't handle the heat": "如果你无法忍受高温",
    "Ikea Shopping Spree": "宜家购物狂欢",
    "Improve your Smile with Surgery": "通过手术改善您的笑容",
    "Impulse Buy a Big Ticket Item": "冲动购买大件物品",
    "Infiltrate NATO": "渗透北约",
    "Inheritance of the Dead": "死者的传承",
    "Initiated into Secret World Trade Club": "加入秘密世界贸易俱乐部",
    "Insane Brothel Night": "疯狂妓院之夜",
    "Inspire Billions of People": "激励数十亿人",
    "Inspire Millions of People": "激励数百万人",
    "Inspire Thousands of People": "激励成千上万的人",
    "intelligent life?": "智能生活？",
    "Internet Fame": "网络名气",
    "Invent a Mind Control Device": "发明精神控制装置",
    "Invent Fusion Energy": "发明聚变能源",
    "Invest in a Sure Thing": "投资确定的事情",
    "Irresponsible Spending": "不负责任的支出",
    "is it worth the money?": "值得这个价吗？",
    "it feels good to give": "给予的感觉很好",
    "it is so you, look it up": "就是你，查一下",
    "it was an accident": "这是一次意外",
    "it was dark in there": "那里很黑",
    "it was easy": "很容易",
    "it was red": "它是红色的",
    "it's a fixer upper": "这是一个固定鞋面",
    "it's about the location": "这是关于位置的",
    "it's all I do": "这就是我所做的一切",
    "it's fast yeah, pretty fast": "很快 是的，相当快",
    "it's for the kids": "这是给孩子们的",
    "it's legit": "这是合法的",
    "it's too expensive..": "太贵..",
    "its the undisputed truth": "这是无可争议的事实",
    "Jeff Bezos - 'I see no suffering here, I make $15 million an hour'": "杰夫·贝佐斯 - “我在这里看不到痛苦，我每小时赚 1500 万美元”",
    "Join the Free Masons": "加入免费共济会",
    "Join the Mars Mission as a Fertility Animal": "作为生育动物加入火星任务",
    "Join the Yearly Free the Turtles From a Turtle Soup Fate Rally": "参加一年一度的“将海龟从海龟汤中解放出来”命运集会",
    "Joys of Wealth": "财富之乐",
    "just bowling, nothing else to find here nope": "只是保龄球，这里没有其他可找到的",
    "just buy lots of this!": "买很多这个！",
    "just google me": "只需谷歌我",
    "keeps your brain busy": "让你的大脑忙碌",
    "Keys to the Federal Reserve": "美联储的钥匙",
    "Kill a Man": "杀一个人",
    "knife on the left?": "刀在左边？",
    "Knit Little Scarves for Little Cats": "为小猫编织小围巾",
    "knock a mu fu ka ouz yo": "敲阿穆夫卡乌兹哟",
    "knockout victory": "淘汰赛胜利",
    "L'eau fait pleurer, le vin fait chanter.": "L'eau fait pleurer，le vin fait chanter。",
    "la lal la la laa": "啦啦啦啦啦啦",
    "Launch an Underground Cage Fighting Empire": "启动地下牢笼战斗帝国",
    "Lay Claim to the Moon": "宣称对月球拥有主权",
    "Learn a New Skill, Winning": "学习新技能，赢得胜利",
    "Learn about a Budget": "了解预算",
    "Learn How to Dance": "学习如何跳舞",
    "Learn Spanish": "学习西班牙语",
    "Learn the Truth": "了解真相",
    "Learn to Code in Python": "学习用 Python 编码",
    "let us help you see": "让我们帮你看看",
    "Let’s go to Timbuktu": "我们去廷巴克图",
    "Let’s make Timbuktu great again!": "让我们让廷巴克图再次伟大！",
    "License a Franchise": "特许经营",
    "life at the top": "生活在顶端",
    "life choices": "人生选择",
    "life is gonna be better": "生活会更好",
    "like my rims?": "就像我的轮圈一样？",
    "Live in a Dump and Clean Sewage Tanks": "住在垃圾场并清洁污水箱",
    "look at those numbers go up!": "看看那些数字上升了！",
    "look into my eyes, you are beautiful": "看着我的眼睛，你很美丽",
    "look into my pants, you are beautiful": "看看我的裤子，你很漂亮",
    "looks like rain..": "看起来像下雨..",
    "Lose 50 Pounds": "减掉 50 磅",
    "Lottery Tickets Every Week!": "每周都有彩票！",
    "Lower your Expenses": "降低您的开支",
    "Lunch Money!": "午饭钱！",
    "Luxury Cruise": "豪华游轮",
    "Make a Record": "做一个记录",
    "Make an Idle Video Game": "制作一款放置类电子游戏",
    "Make Friends": "交朋友",
    "make it block out the sun": "让它遮挡阳光",
    "man or woman, don't matter": "男人或女人，并不重要",
    "Massive Face Tattoo": "脸部大面积纹身",
    "Master Manipulation of Mind": "心灵操控大师",
    "Meal Plan": "进食计划",
    "Meep Meep!": "米普米普！",
    "meow": "喵",
    "mirror, mirror on the wall": "镜子，墙上的镜子",
    "Misunderstanding with the Law": "对法律的误解",
    "Money can't Buy Happiness": "金钱买不到幸福",
    "monkeys are people too": "猴子也是人",
    "Move over Cardi B!": "超越 Cardi B！",
    "move this stuff!": "移动这个东西！",
    "Must never tell...": "绝对不能告诉...",
    "my hero!": "我的英雄！",
    "my name is felix now": "我现在叫菲利克斯",
    "my only friend": "我唯一的朋友",
    "my people, my slaves": "我的人民，我的奴隶",
    "my rules, my wars": "我的规则，我的战争",
    "my soul mate": "我的灵魂伴侣",
    "my Yacht is faster than yours!": "我的游艇比你的快！",
    "Name Yourself God King Emperor": "自称神王皇帝",
    "need more 'happy'..": "需要更多‘快乐’..",
    "need more GPU": "需要更多 GPU",
    "Netflix Subscription": "Netflix 订阅",
    "next 3 days will be down days": "未来 3 天将是停机日",
    "no needles in these haystacks": "这些大海捞针没有针",
    "no pictures please": "没有图片请",
    "no showers!": "没有淋浴！",
    "no vin number on this one": "这个没有 vin 号码",
    "not a soul in sight": "看不见一个人",
    "now hiring": "正在招聘",
    "now I can work!": "现在我可以工作了！",
    "now you need to buy new pants": "现在你需要买新裤子",
    "Off Shore Fund": "离岸基金",
    "ok, but that is gonna cost you...": "好吧，但这会让你付出代价...",
    "Old Money Payouts": "旧钱支出",
    "on a long and lonesome highway": "在漫长而孤独的高速公路上",
    "on foot": "徒步",
    "one day I'll get lucky": "有一天我会很幸运",
    "one small step for me": "对我来说一小步",
    "Only Money, Love Money": "只爱钱，爱钱",
    "only the rich get richer": "只有富人变得更富",
    "Open a Chinese Restaurant": "开一家中餐馆",
    "Open a Corner Store / Money Launderer": "开设街角商店/洗钱活动",
    "Open a Dolphin Zoo": "开设海豚动物园",
    "Open a Farmer's Market Stall": "开设农贸市场摊位",
    "Open a Gym and Pool": "开设健身房和游泳池",
    "Open a Kissing Booth": "开设接吻亭",
    "Open a Popular Nightclub": "开设一家受欢迎的夜总会",
    "Open a Solar Energy Plant": "开设太阳能发电厂",
    "Open a Trendy Social House": "开设时尚社交之家",
    "Open an Etiquette School for Rich Children": "为富家子弟开办礼仪学校",
    "Open an Exclusive Resort for Your Rich Buddies Only": "只为您的有钱伙伴开设专属度假村",
    "Overly Generous": "过于慷慨",
    "OWNED": "拥有",
    "paradise is mine": "天堂是我的",
    "Party with Old Friends": "与老朋友聚会",
    "Passion Project": "激情项目",
    "passive income": "被动收入",
    "Pay a Beggar": "付钱给乞丐",
    "Pay Hush Money": "支付封口费",
    "Pay into a Hedge Fund": "存入对冲基金",
    "Pay off Large Debts": "还清巨额债务",
    "Pay off Small Debts": "还清小额债务",
    "Pay the Blackmail....": "支付勒索费用......",
    "payback's a bitch": "回报是个婊子",
    "peace be with you": "平安与你同在",
    "Pee in an Alley": "在巷子里撒尿",
    "Penny Pinch": "便士紧缩",
    "Pilot Lessons": "试点课程",
    "Plant a Garden": "种植花园",
    "Plant Evidence of a Rivals Crime": "找出竞争对手犯罪的证据",
    "Plastic Surgery": "整形外科",
    "plate of bacon.": "一盘培根。",
    "Play Indie Games": "玩独立游戏",
    "Play Pro Hockey": "打职业曲棍球",
    "please bro?": "请问兄弟？",
    "poof! you’re gone!": "噗！ 你已经走了！",
    "Post a Viral Video": "发布病毒视频",
    "power lies in knowledge": "力量在于知识",
    "Pucker up!": "皱起来！",
    "puff puff pass": "噗噗通行证",
    "Punch Someone You Hate": "殴打你讨厌的人",
    "Purchase": "购买",
    "Purchase a Robot Vacuum": "购买扫地机器人",
    "Purchase a Secret Second Identity": "购买秘密第二身份",
    "Purchase an intimate evening with your favorite celebrity": "与您最喜欢的名人度过一个亲密的夜晚",
    "Purchase Kiribati": "购买基里巴斯",
    "pure skill, and lack of luck": "纯粹的技巧，缺乏运气",
    "put my money to work": "把我的钱用在工作上",
    "put your money to work": "把你的钱用在工作上",
    "rain again?": "又下雨了？",
    "Rapid Unscheduled Disassembly of Your Racecar": "快速、计划外拆卸您的赛车",
    "Read a Good Book": "读一本好书",
    "Realize The World is Unfair": "认识到世界是不公平的",
    "Reduce Spending": "减少开支",
    "reduce your 'cost of living' paid each day'": "减少您每天支付的“生活成本”",
    "Regrettable One Night Stand": "令人遗憾的一夜情",
    "Renovate your Home": "装修你的家",
    "Rent the Burj Kalifa for a Private Party": "租用 Burj Kalifa 举办私人派对",
    "Rescue a Stray Dog": "拯救流浪狗",
    "reusable": "可重复使用的",
    "Romantic Date": "浪漫约会",
    "Santa told me about this warehouse..": "圣诞老人告诉我这个仓库的事。",
    "Save a Life": "拯救生命",
    "Scam a Sucker": "骗个傻瓜",
    "Screw Happiness": "螺丝幸福",
    "Scuba Dive the Great Barrier Reef": "大堡礁水肺潜水",
    "Search for Dropped Coins": "搜索掉落的硬币",
    "See Aliens in the Northern Lights": "在北极光中看到外星人",
    "See the Seven Wonders": "观赏七大奇迹",
    "See your Child Smile": "看到你孩子的微笑",
    "sell flowers from the yard": "卖院子里的花",
    "Sell Handcrafted and Homemade Goods": "出售手工制品和自制商品",
    "Sell off Costly Liabilities": "出售成本高昂的负债",
    "Sell Stolen Cars": "出售被盗汽车",
    "Sell your Body": "出卖你的身体",
    "Sell Your Dignity": "出卖你的尊严",
    "Sell Your Junk Regularly": "定期出售你的垃圾",
    "set my people free": "让我的人民自由",
    "Sex Change Operation, Cause I'm Rich": "变性手术，因为我有钱",
    "shiny": "闪亮的",
    "Short the Markets": "做空市场",
    "Signing Bonus With an Evil Company": "与邪恶公司签约奖金",
    "since we already have mittens...": "因为我们已经有了手套...",
    "Sing in the Rain": "雨中歌唱",
    "Skate on Thin Ice": "在薄冰上滑冰",
    "ski or board?": "滑雪还是滑板？",
    "slobber slobber slobber": "流口水 流口水 流口水",
    "Small Foray into Stocks": "小幅进军股票",
    "Smoke a Joint with Willy Nelson and Snoop Dog": "与威利·纳尔逊和史努比狗一起抽烟",
    "so many choices": "这么多选择",
    "so now you know": "所以现在你知道了",
    "so that's how it works": "这就是它的工作原理",
    "sorry Dave I have National Geographic on the other line": "抱歉，戴夫，另一条线路有国家地理频道",
    "Spend a Year in the Woods": "在树林里度过一年",
    "spend money each day on a fast meal": "每天花钱吃一顿快餐",
    "Spot a Shooting Star": "发现流星",
    "Start a Balloon Animal Farm": "开办气球动物农场",
    "Start a Charitable Business": "开展慈善事业",
    "Start a Construction Company": "创办建筑公司",
    "Start a Cult": "开始邪教",
    "Start a Dog Walking Service": "开始遛狗服务",
    "Start a Farm": "开办农场",
    "Start a Luxury Supersonic Airline": "创办豪华超音速航空公司",
    "Start a Pet Business": "开展宠物生意",
    "Start a Social Media Account": "开设社交媒体帐户",
    "Start a Space Agency": "创办航天局",
    "Start a Trucking Company": "开办货运公司",
    "Start Selling Art": "开始销售艺术品",
    "Start up a Dropshipping Site": "启动直销网站",
    "Steal Gold Bars from the Bank": "从银行偷金条",
    "sun shine and beaches": "阳光和海滩",
    "sunglasses provided": "提供太阳镜",
    "sup cuz?": "超级因为？",
    "sustainable, built to last": "可持续、经久耐用",
    "take 1 every hour and 15 before bed": "每小时 1 粒，睡前 15 粒",
    "Take a Vacation": "去度假",
    "Take Control of the Media": "控制媒体",
    "Take Cooking Classes": "参加烹饪课程",
    "Take the Family to a Wealth Expo": "带家人去一场财富博览",
    "Talk About Your Feelings": "谈谈你的感受",
    "Ten Million Dollar Factory": "千万美元工厂",
    "that is much better": "那好多了",
    "that was a big step": "这是一大步",
    "that was a good haul": "这是一个很好的收获",
    "that was a good read": "这是一本好书",
    "that was INSANE!": "那太疯狂了！",
    "that's a big table": "那是一张大桌子",
    "the advantages of a hereditary Monarchy are self-evident": "世袭君主制的优点是不言而喻的",
    "the astronauts are so attractive...": "宇航员太有魅力了",
    "The Best Advice for Whatever the Price": "无论价格如何，最好的建议",
    "the forest has mushrooms": "森林里有蘑菇",
    "the gods will be pleased": "众神会很高兴",
    "the grass is greener on the other side": "那边的草更绿",
    "the great outdoors beckons": "伟大的户外活动在召唤",
    "the land of the free": "自由之地",
    "the perks of power": "权力的好处",
    "the return is guaranteed": "回报有保证",
    "Therapy": "治疗",
    "there is a crack in everything, that's how the light gets in.": "万物皆有裂痕，那是光线进来的地方。",
    "these royalties are insane!": "这些版税太疯狂了！",
    "they are watching": "他们在看",
    "they can print unlimited of the stuff..": "他们可以打印无限的东西..",
    "they deserve this": "他们应得的",
    "they have insurance against this anyhow": "无论如何他们都有保险",
    "they love me": "他们爱我",
    "they ROCKED!": "他们震撼了！",
    "think like me": "像我一样思考",
    "This fucking guy!": "这个该死的家伙！",
    "this is hard work..": "这很辛苦..",
    "this is me now": "这就是现在的我",
    "This. is. Africa.": "这。 是。 非洲。",
    "time to grow up, welcome to the real world kid": "是时候长大了，欢迎来到现实世界的孩子",
    "Time to pick your carrots!": "是时候摘胡萝卜了！",
    "to be rich": "变得富有",
    "to infinity": "到无限",
    "today shall be a holiday": "今天是假期",
    "tomato? potato!": "番茄？ 土豆！",
    "tomorrow I sleep": "明天我睡觉",
    "top of the line": "线的顶部",
    "Travel Bug": "旅行虫",
    "Trigger an Awkward Social Movement": "引发尴尬的社会运动",
    "true love only comes once": "真爱只有一次",
    "truly a masterpiece!": "真正的杰作！",
    "twice as happy": "双倍快乐",
    "UCFE": "UCFE",
    "unlike those poor kids": "不像那些可怜的孩子",
    "Unlimited Energy!": "无限能量！",
    "Unlocked in Full Version": "完整版解锁",
    "Volunteer at a Soup Kitchen": "在施粥所做志愿者",
    "volunteers needed": "需要志愿者",
    "wanna buy this globe light?": "想买这个地球灯吗？",
    "wanna fight": "想打架",
    "Warehouse Work": "仓库工作",
    "wasn't me": "不是我",
    "we don't need no water": "我们不需要水",
    "Wealthy Man Investment Plan": "富翁投资计划",
    "wear it everywhere I go": "无论我走到哪里都戴着它",
    "Welcome to Idle Trillionaire. Earn Money, Be Happy.": "欢迎来到《闲置亿万富翁》。 赚钱，快乐。",
    "welcome to the club": "欢迎来到俱乐部",
    "what a view": "多么美妙的风景",
    "what a weight off": "体重减轻了多少",
    "what amazing memories": "多么美好的回忆",
    "what can we buy next honey?": "亲爱的，接下来我们可以买什么？",
    "what does it say?": "它说什么？",
    "what doesn't kill you makes you stronger": "那些杀不死你的都会让你变得更强大",
    "what goes up must come down": "有升必有降",
    "where is Master Splinter": "斯普林特大师在哪里",
    "Win a Gold Medal in the Olympics": "在奥运会上赢得金牌",
    "Win a Million Dollars!": "赢取百万美元！",
    "Win a Pie Eating Contest": "赢得吃馅饼比赛",
    "Win a Street Fight": "赢得街头斗殴",
    "Win an All Inclusive Safari": "赢得全包游猎之旅",
    "Win the Slot Machine Jackpot": "赢得老虎机大奖",
    "Win the Yacht Racing Championships": "赢得游艇竞赛锦标赛",
    "wise words from the rich to the rich": "富人对富人的至理名言",
    "with glass walls": "有玻璃墙",
    "with guns": "带枪",
    "Woof woof!": "汪汪！",
    "Work / Work Balance": "工作/工作平衡",
    "worth every penny": "值得每一分钱",
    "Write a Hit Movie": "写一部热门电影",
    "years /": "年 /",
    "Yoga Lesson": "瑜伽课",
    "you are welcome": "不客气",
    "You can now tango like a pro!": "您现在可以像专业人士一样探戈！",
    "You found a great tenant!": "你找到了一个很棒的租客！",
    "you guys know any whales?": "你们认识鲸鱼吗？",
    "you have passed the test, you will be rewarded handsomely": "你通过了考验，你将获得丰厚的奖励",
    "You Know You're Rich When You're Buying This": "当你买这个的时候你就知道你很有钱了",
    "you learned how to make sushi!": "你学会了如何做寿司！",
    "you never saw nothing": "你什么也没看见",
    "you work hard for your money": "你为你的钱而努力工作",
    "Your Goal is to Earn a Trillion or More Dollars": "您的目标是赚取一万亿或更多美元",
    "Your house is so clean now!": "你家现在真干净啊！",
    "your income can grow only to the extent that you do": "你的收入只能在你做的范围内增长",
    "yum": "嗯",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\+([\d\.,]+)😄$/,
    /^\-([\d\.,]+)😄$/,
    /^\-\$([\d\.,]+)😄$/,
    /^\+([\d\.,]+)💰$/,
    /^\+\$([\d\.,]+)💰$/,
    /^\-([\d\.,]+)💰$/,
    /^\-\$([\d\.,]+)💰$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\+([\d\.,]+)😄\/ day$/, '\+$1😄\/ 天'],
    [/^\+([\d\.,]+) 😄\/ day$/, '\+$1 😄\/ 天'],
    [/^\-([\d\.,]+)😄\/ day$/, '\-$1😄\/ 天'],
    [/^\$([\d\.,]+) \/ hour$/, '\$ $1 \/ 小时'],
    [/^\+\$([\d\.,]+)💰\/ hour$/, '\+\$ $1💰\/ 小时'],
    [/^\-\$([\d\.,]+)💰\/ hour$/, '\-\$ $1💰\/ 小时'],
    [/^\+\$([\d\.,]+)💰 annually$/, '\+\$ $1💰 每年'],
    [/^\-\$([\d\.,]+)💰 annually$/, '\-\$ $1💰 每年'],
    [/^\+\$([\d\.,]+)💰cost of living$/, '\+\$ $1💰 生活成本'],
    [/^\-\$([\d\.,]+)💰cost of living$/, '\-\$ $1💰 生活成本'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);