/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "/ day": "/ 天",
    "'I am so hungry, Thanks Mom!'": "",
    "*🔎All Cards": "*🔎全部卡片",
    "Broken Leg": "断腿",
    "Buy a Car": "买辆车",
    "💰Bank Account:": "💰银行账户:",
    "-Infuence-Za Fashion 19-": "-影响-Za时尚19-",
    "'you are worthless, worse than worthless' - the rich to the poor": "“你一文不值，比一文不值还要糟糕”——富人对穷人",
    "$8.9 million a year out of her!": "她一年 $8.9 million！",
    "1 liberty bell, 3 liberty bells": "1 个自由钟、3 个自由钟",
    "10 Million Subscribers on YouTube": "YouTube 上有 1000 万订阅者",
    "A Big Night Out": "一个美好的夜晚",
    "A Brush with Death": "与死亡擦肩而过",
    "a few years in the blink of an eye": "转眼几年",
    "a massive group of dollar bills": "一大堆美元钞票",
    "A Nice Necklace": "一条漂亮的项链",
    "A Real Saver": "真正的节省者",
    "A REALLY Good Day!": "真是美好的一天！",
    "about time...": "关于时间...",
    "Achieve a Life Long Goal": "实现终生目标",
    "after the trial, throw away the key": "试用后，扔掉钥匙",
    "Alaskan Adventure": "阿拉斯加探险",
    "all night long, star of the floor": "整夜，地板之星",
    "all that planning paid off": "所有的计划都得到了回报",
    "all you can drink": "无限畅饮",
    "always on the lookout": "始终保持警惕",
    "am I successful enough yet?": "我还足够成功吗？",
    "Amen!": "阿门！",
    "an ayahuasca retreat!": "死藤水静修！",
    "and terrible choices..": "和可怕的选择..",
    "and these are my all natural organic gluten free picture frames": "这些是我的全天然有机无麸质相框",
    "and this next song is about...": "下一首歌曲是关于...",
    "Annual Bonus = $0": "年度奖金 = $0",
    "Annual Christmas Heist": "一年一度的圣诞抢劫",
    "Annual Season Pass - The Ski Hill": "年度季票 - 滑雪场",
    "another world down here": "这里是另一个世界",
    "Antarctic Expedition": "南极探险",
    "anyone looking?": "有人在找吗？",
    "are you kidding me Dina?": "迪娜，你在开玩笑吗？",
    "atop her, my statue, golden throne, diamond upon my crown": "在她的顶上，我的雕像，金色的王座，我的王冠上有钻石",
    "Attract a Lover": "吸引情人",
    "Australia, under my thumb": "澳大利亚，在我的掌控之中",
    "Bad Decisions": "错误的决定",
    "bare knuckle": "裸关节",
    "Bathe in a Million in Cash, then Burn it": "沐浴一百万现金，然后烧掉它",
    "battered old thing": "破旧的东西",
    "be like me": "和我一样",
    "Beat Cookie Clicker": "击败饼干唱首歌",
    "Become a Crazy Cat Person": "成为一个疯狂的猫人",
    "Become a Famous Magician": "成为著名魔术师",
    "Become an Influencer and Film Dance Clips in Public": "成为有影响力的人并在公共场合拍摄舞蹈片段",
    "Become Mayor of Timbuktu": "成为廷巴克图市长",
    "Become Spiritual": "变得有灵性",
    "Become Vegan": "成为素食主义者",
    "begin production": "开始生产",
    "Begin Work.. Secret Work": "开始工作..秘密工作",
    "Bet It All On Red": "全力押注红色",
    "better wash before you wear": "穿之前最好先洗一下",
    "Betting on Underground Cage Fights": "投注地下笼斗",
    "Big Loan": "大额贷款",
    "Birthday Gift": "生日礼物",
    "Blackmail the POTUS": "勒索美国总统",
    "BOGO baby!": "波戈宝贝！",
    "boom": "繁荣",
    "boost you productivity rates": "提高您的生产率",
    "bow to me, you dumb peasants": "向我鞠躬，你们这些愚蠢的农民",
    "bow to my greatness": "向我的伟大低头",
    "brand new": "全新",
    "bravo on being so kind!": "太善良了！",
    "Breakfast in Bed": "在床上吃早餐",
    "Bribe a Cop": "贿赂警察",
    "Bribe the Royal Family": "贿赂皇室",
    "bring your snorkel": "带上你的通气管",
    "Build a 20,000 Car Parkade for Your Home": "为您的家建造一个可容纳 20,000 个停车位的停车场",
    "Build a Crypto Currency Farm": "建立一个加密货币农场",
    "Build a Giant Bathtub": "建造一个巨型浴缸",
    "Build a Mountain from Diamonds": "用钻石建造一座山",
    "Build a Personal Hockey Rink": "建造个人曲棍球场",
    "Build an Underwater Hotel": "建造水下酒店",
    "but I thought..": "但我想..",
    "but never tell": "但永远不要告诉",
    "Buy 1000 Hamsters": "购买 1000 只仓鼠",
    "Buy a Bike": "买一辆自行车",
    "Buy a Cannabis Shop": "购买大麻店",
    "Buy a Computer": "购买电脑",
    "Buy a Dividend Fund": "购买股息基金",
    "Buy a House in Panama": "在巴拿马买房子",
    "Buy a Kitten": "买一只小猫",
    "Buy a Manhattan Parking Spot": "购买曼哈顿停车位",
    "Buy a Mansion In the Boonies": "在布尼区购买豪宅",
    "Buy a Mansion on a Lake": "购买湖边豪宅",
    "Buy a Painting by a Famous Artist": "购买著名艺术家的画作",
    "Buy a Patagonia Jacket": "买一件巴塔哥尼亚夹克",
    "Buy a Private Jet": "购买私人飞机",
    "Buy a Race Car": "买一辆赛车",
    "Buy a Really Nice House for Mom and Dad": "为爸爸妈妈买一栋非常漂亮的房子",
    "Buy a Rental Property": "购买出租物业",
    "Buy a Super-Computer Laptop, for Productivity and gaming": "购买超级电脑笔记本电脑，提高工作效率和玩游戏",
    "Buy a Surfboard": "买一块冲浪板",
    "Buy a Tiny Downtown One Room Condo": "购买一套小型市中心单间公寓",
    "Buy a tiny Yacht": "买一艘小型游艇",
    "Buy a Very Nice Wake Surf Boat": "购买一艘非常好的尾波冲浪船",
    "Buy a Vineyard in France": "在法国购买葡萄园",
    "Buy All Your Friends Cars": "购买你所有朋友的汽车",
    "Buy an Amateur Soccer Team": "购买一支业余足球队",
    "Buy an Investment Bank": "购买投资银行",
    "Buy an Ultra Fancy Car": "购买一辆超豪华的汽车",
    "Buy Extremely Fancy Shoes": "买非常漂亮的鞋子",
    "Buy Friends So You Can Scam them Later": "购买好友，以便以后可以诈骗他们",
    "Buy Graff Diamonds Hallucination Watch": "购买格拉夫钻石幻觉腕表",
    "Buy Long Term Bonds": "购买长期债券",
    "Buy Mount Everest, Make It Yours": "购买珠穆朗玛峰，让它成为你的",
    "Buy New Friends": "购买新朋友",
    "Buy Starter House": "购买入门房",
    "Buy Success": "购买成功",
    "Can I 'borrow' a Hundred G, G?": "我可以‘借’一百G吗？",
    "Can I 'borrow' an Easy Milly, Billy?": "我可以“借”一个简单的米莉吗，比利？",
    "can't help myself": "情不自禁",
    "Cannot Afford": "不能负担",
    "Capture Rare Footage": "捕捉稀有镜头",
    "Cash in on Race Privilege": "兑现比赛特权",
    "catch some waves": "抓住一些波浪",
    "Catch that Pesky Road Runner": "抓住那个讨厌的公路跑者",
    "cats only, all cats": "仅猫，所有猫",
    "cause I don't want to be embarrassed by them": "因为我不想让他们感到尴尬",
    "Cheat on Your Spouse with a Model": "用模特欺骗你的配偶",
    "chicken fried rice?": "鸡肉炒饭？",
    "Click on cards to purchase. Cards affect the rate that you generate $ and happy": "点击卡片即可购买。 卡会影响你产生美元和快乐的比率",
    "Climb a Mountain": "爬山",
    "Collect Child Support Baby!": "收集儿童抚养费宝贝！",
    "Collect Rare, Vintage Comics": "收集稀有的复古漫画",
    "College Diploma": "大学文凭",
    "Come Out of the Closet": "出柜",
    "coming to you from Earth": "从地球来到你身边",
    "Conduct an Annual Blood Ritual": "进行一年一度的献血仪式",
    "Construct a Bowling Alley": "建造一个保龄球馆",
    "Construct the Tallest Building in the World!": "建造世界上最高的建筑！",
    "Control Wall Street": "控制华尔街",
    "convenience, elegance": "便利、优雅",
    "Corner the Paper Route Market": "垄断纸路市场",
    "cost of doing business": "做生意的成本",
    "Cost of living: $": "生活费用：$",
    "coupon hunter": "优惠券猎人",
    "Crack Addiction": "破解成瘾",
    "create a human-level AI": "创造人类水平的人工智能",
    "Create a Religion of You": "创造你的宗教",
    "Create an Online Fashion Boutique": "创建在线时装精品店",
    "Creep with the Girl Next Door": "与邻家女孩一起爬行",
    "customers first": "客户至上",
    "cute lil guys": "可爱的小家伙们",
    "days /": "天 /",
    "Debts Forgiven": "债务被免除",
    "deserved it but it was worth it": "这是应得的，但这是值得的",
    "Design a Rocket Ship": "设计一艘火箭飞船",
    "Design and Sell Print-on-Demand T-shirts": "设计和销售按需印刷 T 恤",
    "Design Pyramid Scheme, Deploy Pyramid Scheme": "设计金字塔计划、部署金字塔计划",
    "desperate times": "绝望的时刻",
    "Develop Mood Enhancing Pills": "开发情绪增强药",
    "didn't read the small print": "没有阅读小字",
    "Dig in the $#!%, Literally": "从字面上看，挖掘 $#!%",
    "Dirty Money, But Good Money": "脏钱，但好钱",
    "Discover Atlantis": "探索亚特兰蒂斯",
    "Discover Life on Mars": "发现火星上的生命",
    "Discover the Next American Idol": "发现下一个美国偶像",
    "do not even look at me...": "连看都不看我一眼...",
    "Do Someones Dirty Work": "做一些肮脏的工作",
    "Don’t forget to pickup the poop": "别忘了捡起便便",
    "Donate your Liver": "捐献你的肝脏",
    "Drink Away Your Sorrows": "喝掉你的悲伤",
    "Drinking Habit": "饮酒习惯",
    "Earn a Favor from a Hot Shot Politician": "赢得热门政客的青睐",
    "Earn What Jeff Bezos Earns": "赚取杰夫·贝索斯的收入",
    "Earn your Masters": "获得硕士学位",
    "Eat a Banana": "吃一根香蕉",
    "End World Suffering": "结束世界苦难",
    "Enslave a Lost People": "奴役迷失的人民",
    "Enter a Beauty Contest and Lose": "参加选美比赛并输掉比赛",
    "Enter the World of Extreme Couponing": "进入极限优惠券的世界",
    "ew.. what are you?": "呃..你是什么？",
    "excuse me sir...": "对不起，先生...",
    "exfoliate the flesh": "去角质",
    "Expensive Date": "昂贵的约会",
    "Expensive Habits": "昂贵的习惯",
    "Experience Your Darkest Fantasy": "体验你最黑暗的幻想",
    "Extort the Competition": "勒索竞争",
    "Family Reunion": "家庭团聚",
    "fear me": "怕我",
    "Featuring Superman as the Weakest Man in the World": "超人是世界上最弱的人",
    "Fight for the UFC Heavyweight Title": "争夺UFC重量级冠军",
    "Fight to the Death and Win": "战斗至死并取得胜利",
    "fill it with super cars": "装满超级跑车",
    "fill it with yachts and bubbles": "用游艇和泡泡填满它",
    "finally free of the peasant scum": "终于摆脱了农民渣",
    "finally some money": "终于有钱了",
    "Financial Education": "理财教育",
    "Financial Goals": "财务目标",
    "Find a Message in a Bottle": "寻找瓶中信",
    "Find a Potato Chip in the Shape of Jesus": "找到耶稣形状的薯片",
    "Find a Tax Loophole": "寻找税务漏洞",
    "finding balance": "找到平衡",
    "Fire up the grill": "点燃烤架",
    "First Kiss": "初吻",
    "fly little birds! be free": "小鸟飞翔吧！ 是自由的",
    "Focus on Your Career": "专注于你的职业生涯",
    "follow your heart": "跟随你的心",
    "for hipsters only": "仅限潮人",
    "for money": "为了钱",
    "for tax purposes": "出于税收目的",
    "for the birthdays I deserve": "为了我应得的生日",
    "for the future": "为将来",
    "Form a Gambling Addiction": "养成赌博成瘾的习惯",
    "Form a Medical Cannabis Producer": "组建医用大麻生产商",
    "Form a Sovereign Country": "建立主权国家",
    "free drinks for friends": "为朋友提供免费饮料",
    "Free Your Harem": "解放你的后宫",
    "freedom": "自由",
    "fresh air": "新鲜空气",
    "fries with that?": "炸薯条吗？",
    "Full-Time Job": "全职工作",
    "fully 'legal'": "完全“合法”",
    "Fund a Private Moon Mission": "资助私人月球任务",
    "Fund a Rainforest Renewal Project": "资助雨林更新项目",
    "Fund Unethical Research Studies": "资助不道德的研究",
    "Gain Their Blind Trust": "获得他们的盲目信任",
    "get a bonus on the first day of every year": "每年第一天获得奖金",
    "Get a Driver's License": "获得驾驶执照",
    "Get a Lawn Mowing Job": "找到一份割草工作",
    "Get a Roofing Job": "找一份屋顶工作",
    "Get a second sexual organ": "获得第二性器官",
    "Get Arrested for Streaking Past McDonalds": "因裸奔麦当劳而被捕",
    "Get Away with Insurance Fraud": "远离保险欺诈",
    "Get Caught Checking Someone Out": "结账时被抓",
    "Get delivering!": "快去送货吧！",
    "Get Elected as Chairman of the Board": "当选为董事长",
    "Get Flexible": "变得灵活",
    "Get Mugged": "被打劫",
    "Get Punched in the Face": "被打脸",
    "Get Scammed": "被骗",
    "Get Sweet Revenge on Montezuma": "对蒙特祖玛进行甜蜜的复仇",
    "Get Two Hole in Ones in a Row": "连续两个洞",
    "Give your Child 25 Billion Dollars": "给你的孩子250亿美元",
    "Go Dancing": "去跳舞",
    "Go for Walks": "去散步",
    "Go Global Straight Up": "直接走向全球",
    "Go Hunting in Alaska and Nebraska": "去阿拉斯加和内布拉斯加州狩猎",
    "Go on Sky Diving Retreat": "继续跳伞静修",
    "Go out for a Stupidly Expensive Dinner": "出去吃一顿贵得离谱的晚餐",
    "Go to a Concert": "去听音乐会",
    "Go to Low Earth Orbit on a Virgin Galactic Space Plane": "乘坐维珍银河太空飞机前往近地轨道",
    "Go to the Spa": "去水疗中心",
    "Good Karma": "善业",
    "good kids": "好孩子",
    "Good Luck in the Markets": "祝市场好运",
    "got my shots!": "我的镜头得到了！",
    "gotta start somewhere": "必须从某个地方开始",
    "Graduate High School": "研究生高中",
    "grand opening discount": "开业折扣",
    "Gravel Kickers United": "碎石踢球者联队",
    "great food, every day": "美味的食物，每一天",
    "ha ha sucka": "哈哈 苏卡",
    "hamburger buns never looked so good": "汉堡包从未看起来如此美味",
    "Hang Glide Naked Over a Volcano": "赤裸悬挂在火山上滑翔",
    "happiness can buy money": "幸福可以买钱",
    "Happy 😄: 122.": "快乐😄：122。",
    "Happy Booster": "快乐助推器",
    "Hard Work Pays Off": "付出就有收获",
    "Have a Great Monument Built in Your Honor": "以您的名义建造一座伟大的纪念碑",
    "Have Beautiful Children": "拥有美丽的孩子",
    "have you beaten cookie clicker?": "你打败过饼干点击器吗？",
    "Help a Stranger": "帮助陌生人",
    "Help Save Starving Children": "帮助拯救饥饿的儿童",
    "helping others help themselves": "帮助别人帮助自己",
    "Hire a Maid": "聘请女佣",
    "Hire a Master Chef": "聘请一位主厨",
    "Hire Body Guards": "雇用保镖",
    "Hire the Best Therapist for Psychopath": "为精神病患者聘请最好的治疗师",
    "Hola!": "你好！",
    "Horde your Wealth": "聚集你的财富",
    "Host a Summer BBQ for all your Friends": "为您所有的朋友举办夏季烧烤",
    "hot tar": "热焦油",
    "hours passed": "几个小时过去了",
    "how can you lose?": "你怎么能输呢？",
    "how much are you thinking?": "你想多少？",
    "I am a bird now": "我现在是一只鸟",
    "I am a good person now": "我现在是一个好人了",
    "I am good for it": "我很擅长",
    "I AM SO H A P P Y !": "我太高兴了 ！",
    "I am the BIRD! am I?": "我是鸟！ 我是吗？",
    "I appreciate the work the devs do": "我很欣赏开发人员所做的工作",
    "I brought a gun to a knife fight": "我带着枪参加刀战",
    "I can not believe they bought it!": "我不敢相信他们买了它！",
    "I can't stop smiling": "我无法停止微笑",
    "I demand a return on my investment!": "我要求我的投资得到回报！",
    "I did it!": "我做到了！",
    "I don't do dirty work": "我不做肮脏的工作",
    "I don't even miss it": "我什至不想念它",
    "I don't know what you are talking about": "我不知道你在说什么",
    "I earned this": "我赚到了这个",
    "I feel better now": "我现在感觉好多了",
    "I felt a spark...": "我感觉到了火花...",
    "I guess I'll take it": "我想我会接受它",
    "I hate you all!": "我恨你们！",
    "I have conquered Everest": "我已经征服了珠穆朗玛峰",
    "I have no social life": "我没有社交生活",
    "I hope I don't regret this": "我希望我不会为此后悔",
    "I just had a feeling..": "我只是有一种感觉..",
    "I just know a guy in Office, soooo..": "我只认识办公室里的一个人，所以..",
    "I make wish now": "我现在许愿",
    "I missed jumping": "我错过了跳跃",
    "I need cash not smiles": "我需要现金而不是微笑",
    "I need the money": "我需要那些钱",
    "I only use my arms": "我只用我的手臂",
    "I pay you, you let me win": "我付钱给你，你让我赢",
    "I think I like myself now": "我想我喜欢现在的自己",
    "I was born with this": "我生来就有这个",
    "I was happy before, but now that we met I am SO HAPPY!": "以前我很高兴，但现在我们见面了，我很高兴！",
    "I will ruin you": "我会毁了你",
    "I'll do anything": "我会做任何事",
    "I'll give you bacon": "我给你培根",
    "I'll give you whatever you want!": "你想要什么我都给你！",
    "I'll pay this time, again guys": "这次我会付钱的，伙计们",
    "I'll pay you back...": "我会还给你的...",
    "I'm just that important": "我就是这么重要",
    "I'm Rich and I know it": "我很富有，我知道这一点",
    "I'm so embarrassed": "我好尴尬",
    "I'm so weak now I feel strong": "我现在很虚弱，我感觉自己很坚强",
    "I'm talkin full splits, both ways": "我正在谈论完全分裂，双向",
    "I'm telling you! I saw what I saw!": "我告诉你！ 我看到了我所看到的！",
    "Idle Trillionaire": "闲置亿万富翁",
    "If only...": "要是...",
    "if they pay, I sell": "如果他们付钱，我就卖",
    "if you can't handle the heat": "如果你无法忍受高温",
    "Ikea Shopping Spree": "宜家购物狂欢",
    "Improve your Smile with Surgery": "通过手术改善您的笑容",
    "Impulse Buy a Big Ticket Item": "冲动购买大件物品",
    "Infiltrate NATO": "渗透北约",
    "Inheritance of the Dead": "死者的传承",
    "Initiated into Secret World Trade Club": "加入秘密世界贸易俱乐部",
    "Insane Brothel Night": "疯狂妓院之夜",
    "Inspire Billions of People": "激励数十亿人",
    "Inspire Millions of People": "激励数百万人",
    "Inspire Thousands of People": "激励成千上万的人",
    "intelligent life?": "智能生活？",
    "Internet Fame": "网络名气",
    "Invent a Mind Control Device": "发明精神控制装置",
    "Invent Fusion Energy": "发明聚变能源",
    "Invest in a Sure Thing": "投资确定的事情",
    "Irresponsible Spending": "不负责任的支出",
    "is it worth the money?": "值得这个价吗？",
    "it feels good to give": "给予的感觉很好",
    "it is so you, look it up": "就是你，查一下",
    "it was an accident": "这是一次意外",
    "it was dark in there": "那里很黑",
    "it was easy": "很容易",
    "it was red": "它是红色的",
    "it's a fixer upper": "这是一个固定鞋面",
    "it's about the location": "这是关于位置的",
    "it's all I do": "这就是我所做的一切",
    "it's fast yeah, pretty fast": "很快 是的，相当快",
    "it's for the kids": "这是给孩子们的",
    "it's legit": "这是合法的",
    "it's too expensive..": "太贵..",
    "its the undisputed truth": "这是无可争议的事实",
    "Jeff Bezos - 'I see no suffering here, I make $15 million an hour'": "杰夫·贝佐斯 - “我在这里看不到痛苦，我每小时赚 1500 万美元”",
    "Join the Free Masons": "加入免费共济会",
    "Join the Mars Mission as a Fertility Animal": "作为生育动物加入火星任务",
    "Join the Yearly Free the Turtles From a Turtle Soup Fate Rally": "参加一年一度的“将海龟从海龟汤中解放出来”命运集会",
    "Joys of Wealth": "财富之乐",
    "just bowling, nothing else to find here nope": "只是保龄球，这里没有其他可找到的",
    "just buy lots of this!": "买很多这个！",
    "just google me": "只需谷歌我",
    "keeps your brain busy": "让你的大脑忙碌",
    "Keys to the Federal Reserve": "美联储的钥匙",
    "Kill a Man": "杀一个人",
    "knife on the left?": "刀在左边？",
    "Knit Little Scarves for Little Cats": "为小猫编织小围巾",
    "knock a mu fu ka ouz yo": "敲阿穆夫卡乌兹哟",
    "knockout victory": "淘汰赛胜利",
    "L'eau fait pleurer, le vin fait chanter.": "L'eau fait pleurer，le vin fait chanter。",
    "la lal la la laa": "啦啦啦啦啦啦",
    "Launch an Underground Cage Fighting Empire": "启动地下牢笼战斗帝国",
    "Lay Claim to the Moon": "宣称对月球拥有主权",
    "Learn a New Skill, Winning": "学习新技能，赢得胜利",
    "Learn about a Budget": "了解预算",
    "Learn How to Dance": "学习如何跳舞",
    "Learn Spanish": "学习西班牙语",
    "Learn the Truth": "了解真相",
    "Learn to Code in Python": "学习用 Python 编码",
    "let us help you see": "让我们帮你看看",
    "Let’s go to Timbuktu": "我们去廷巴克图",
    "Let’s make Timbuktu great again!": "让我们让廷巴克图再次伟大！",
    "License a Franchise": "特许经营",
    "life at the top": "生活在顶端",
    "life choices": "人生选择",
    "life is gonna be better": "生活会更好",
    "like my rims?": "就像我的轮圈一样？",
    "Live in a Dump and Clean Sewage Tanks": "住在垃圾场并清洁污水箱",
    "look at those numbers go up!": "看看那些数字上升了！",
    "look into my eyes, you are beautiful": "看着我的眼睛，你很美丽",
    "look into my pants, you are beautiful": "看看我的裤子，你很漂亮",
    "looks like rain..": "看起来像下雨..",
    "Lose 50 Pounds": "减掉 50 磅",
    "Lottery Tickets Every Week!": "每周都有彩票！",
    "Lower your Expenses": "降低您的开支",
    "Lunch Money!": "午饭钱！",
    "Luxury Cruise": "豪华游轮",
    "Make a Record": "做一个记录",
    "Make an Idle Video Game": "制作一款放置类电子游戏",
    "Make Friends": "交朋友",
    "make it block out the sun": "让它遮挡阳光",
    "man or woman, don't matter": "男人或女人，并不重要",
    "Massive Face Tattoo": "脸部大面积纹身",
    "Master Manipulation of Mind": "心灵操控大师",
    "Meal Plan": "进食计划",
    "Meep Meep!": "米普米普！",
    "meow": "喵",
    "mirror, mirror on the wall": "镜子，墙上的镜子",
    "Misunderstanding with the Law": "对法律的误解",
    "Money can't Buy Happiness": "金钱买不到幸福",
    "monkeys are people too": "猴子也是人",
    "Move over Cardi B!": "超越 Cardi B！",
    "move this stuff!": "移动这个东西！",
    "Must never tell...": "绝对不能告诉...",
    "my hero!": "我的英雄！",
    "my name is felix now": "我现在叫菲利克斯",
    "my only friend": "我唯一的朋友",
    "my people, my slaves": "我的人民，我的奴隶",
    "my rules, my wars": "我的规则，我的战争",
    "my soul mate": "我的灵魂伴侣",
    "my Yacht is faster than yours!": "我的游艇比你的快！",
    "Name Yourself God King Emperor": "自称神王皇帝",
    "need more 'happy'..": "需要更多‘快乐’..",
    "need more GPU": "需要更多 GPU",
    "Netflix Subscription": "Netflix 订阅",
    "next 3 days will be down days": "未来 3 天将是停机日",
    "no needles in these haystacks": "这些大海捞针没有针",
    "no pictures please": "没有图片请",
    "no showers!": "没有淋浴！",
    "no vin number on this one": "这个没有 vin 号码",
    "not a soul in sight": "看不见一个人",
    "now hiring": "正在招聘",
    "now I can work!": "现在我可以工作了！",
    "now you need to buy new pants": "现在你需要买新裤子",
    "Off Shore Fund": "离岸基金",
    "ok, but that is gonna cost you...": "好吧，但这会让你付出代价...",
    "Old Money Payouts": "旧钱支出",
    "on a long and lonesome highway": "在漫长而孤独的高速公路上",
    "on foot": "徒步",
    "one day I'll get lucky": "有一天我会很幸运",
    "one small step for me": "对我来说一小步",
    "Only Money, Love Money": "只爱钱，爱钱",
    "only the rich get richer": "只有富人变得更富",
    "Open a Chinese Restaurant": "开一家中餐馆",
    "Open a Corner Store / Money Launderer": "开设街角商店/洗钱活动",
    "Open a Dolphin Zoo": "开设海豚动物园",
    "Open a Farmer's Market Stall": "开设农贸市场摊位",
    "Open a Gym and Pool": "开设健身房和游泳池",
    "Open a Kissing Booth": "开设接吻亭",
    "Open a Popular Nightclub": "开设一家受欢迎的夜总会",
    "Open a Solar Energy Plant": "开设太阳能发电厂",
    "Open a Trendy Social House": "开设时尚社交之家",
    "Open an Etiquette School for Rich Children": "为富家子弟开办礼仪学校",
    "Open an Exclusive Resort for Your Rich Buddies Only": "只为您的有钱伙伴开设专属度假村",
    "Overly Generous": "过于慷慨",
    "OWNED": "拥有",
    "paradise is mine": "天堂是我的",
    "Party with Old Friends": "与老朋友聚会",
    "Passion Project": "激情项目",
    "passive income": "被动收入",
    "Pay a Beggar": "付钱给乞丐",
    "Pay Hush Money": "支付封口费",
    "Pay into a Hedge Fund": "存入对冲基金",
    "Pay off Large Debts": "还清巨额债务",
    "Pay off Small Debts": "还清小额债务",
    "Pay the Blackmail....": "支付勒索费用......",
    "payback's a bitch": "回报是个婊子",
    "peace be with you": "平安与你同在",
    "Pee in an Alley": "在巷子里撒尿",
    "Penny Pinch": "便士紧缩",
    "Pilot Lessons": "试点课程",
    "Plant a Garden": "种植花园",
    "Plant Evidence of a Rivals Crime": "找出竞争对手犯罪的证据",
    "Plastic Surgery": "整形外科",
    "plate of bacon.": "一盘培根。",
    "Play Indie Games": "玩独立游戏",
    "Play Pro Hockey": "打职业曲棍球",
    "please bro?": "请问兄弟？",
    "poof! you’re gone!": "噗！ 你已经走了！",
    "Post a Viral Video": "发布病毒视频",
    "power lies in knowledge": "力量在于知识",
    "Pucker up!": "皱起来！",
    "puff puff pass": "噗噗通行证",
    "Punch Someone You Hate": "殴打你讨厌的人",
    "Purchase": "购买",
    "Purchase a Robot Vacuum": "购买扫地机器人",
    "Purchase a Secret Second Identity": "购买秘密第二身份",
    "Purchase an intimate evening with your favorite celebrity": "与您最喜欢的名人度过一个亲密的夜晚",
    "Purchase Kiribati": "购买基里巴斯",
    "pure skill, and lack of luck": "纯粹的技巧，缺乏运气",
    "put my money to work": "把我的钱用在工作上",
    "put your money to work": "把你的钱用在工作上",
    "rain again?": "又下雨了？",
    "Rapid Unscheduled Disassembly of Your Racecar": "快速、计划外拆卸您的赛车",
    "Read a Good Book": "读一本好书",
    "Realize The World is Unfair": "认识到世界是不公平的",
    "Reduce Spending": "减少开支",
    "reduce your 'cost of living' paid each day'": "减少您每天支付的“生活成本”",
    "Regrettable One Night Stand": "令人遗憾的一夜情",
    "Renovate your Home": "装修你的家",
    "Rent the Burj Kalifa for a Private Party": "租用 Burj Kalifa 举办私人派对",
    "Rescue a Stray Dog": "拯救流浪狗",
    "reusable": "可重复使用的",
    "Romantic Date": "浪漫约会",
    "Santa told me about this warehouse..": "圣诞老人告诉我这个仓库的事。",
    "Save a Life": "拯救生命",
    "Scam a Sucker": "骗个傻瓜",
    "Screw Happiness": "螺丝幸福",
    "Scuba Dive the Great Barrier Reef": "大堡礁水肺潜水",
    "Search for Dropped Coins": "搜索掉落的硬币",
    "See Aliens in the Northern Lights": "在北极光中看到外星人",
    "See the Seven Wonders": "观赏七大奇迹",
    "See your Child Smile": "看到你孩子的微笑",
    "sell flowers from the yard": "卖院子里的花",
    "Sell Handcrafted and Homemade Goods": "出售手工制品和自制商品",
    "Sell off Costly Liabilities": "出售成本高昂的负债",
    "Sell Stolen Cars": "出售被盗汽车",
    "Sell your Body": "出卖你的身体",
    "Sell Your Dignity": "出卖你的尊严",
    "Sell Your Junk Regularly": "定期出售你的垃圾",
    "set my people free": "让我的人民自由",
    "Sex Change Operation, Cause I'm Rich": "变性手术，因为我有钱",
    "shiny": "闪亮的",
    "Short the Markets": "做空市场",
    "Signing Bonus With an Evil Company": "与邪恶公司签约奖金",
    "since we already have mittens...": "因为我们已经有了手套...",
    "Sing in the Rain": "雨中歌唱",
    "Skate on Thin Ice": "在薄冰上滑冰",
    "ski or board?": "滑雪还是滑板？",
    "slobber slobber slobber": "流口水 流口水 流口水",
    "Small Foray into Stocks": "小幅进军股票",
    "Smoke a Joint with Willy Nelson and Snoop Dog": "与威利·纳尔逊和史努比狗一起抽烟",
    "so many choices": "这么多选择",
    "so now you know": "所以现在你知道了",
    "so that's how it works": "这就是它的工作原理",
    "sorry Dave I have National Geographic on the other line": "抱歉，戴夫，另一条线路有国家地理频道",
    "Spend a Year in the Woods": "在树林里度过一年",
    "spend money each day on a fast meal": "每天花钱吃一顿快餐",
    "Spot a Shooting Star": "发现流星",
    "Start a Balloon Animal Farm": "开办气球动物农场",
    "Start a Charitable Business": "开展慈善事业",
    "Start a Construction Company": "创办建筑公司",
    "Start a Cult": "开始邪教",
    "Start a Dog Walking Service": "开始遛狗服务",
    "Start a Farm": "开办农场",
    "Start a Luxury Supersonic Airline": "创办豪华超音速航空公司",
    "Start a Pet Business": "开展宠物生意",
    "Start a Social Media Account": "开设社交媒体帐户",
    "Start a Space Agency": "创办航天局",
    "Start a Trucking Company": "开办货运公司",
    "Start Selling Art": "开始销售艺术品",
    "Start up a Dropshipping Site": "启动直销网站",
    "Steal Gold Bars from the Bank": "从银行偷金条",
    "sun shine and beaches": "阳光和海滩",
    "sunglasses provided": "提供太阳镜",
    "sup cuz?": "超级因为？",
    "sustainable, built to last": "可持续、经久耐用",
    "take 1 every hour and 15 before bed": "每小时 1 粒，睡前 15 粒",
    "Take a Vacation": "去度假",
    "Take Control of the Media": "控制媒体",
    "Take Cooking Classes": "参加烹饪课程",
    "Take the Family to a Wealth Expo": "带家人去一场财富博览",
    "Talk About Your Feelings": "谈谈你的感受",
    "Ten Million Dollar Factory": "千万美元工厂",
    "that is much better": "那好多了",
    "that was a big step": "这是一大步",
    "that was a good haul": "这是一个很好的收获",
    "that was a good read": "这是一本好书",
    "that was INSANE!": "那太疯狂了！",
    "that's a big table": "那是一张大桌子",
    "the advantages of a hereditary Monarchy are self-evident": "世袭君主制的优点是不言而喻的",
    "the astronauts are so attractive...": "宇航员太有魅力了",
    "The Best Advice for Whatever the Price": "无论价格如何，最好的建议",
    "the forest has mushrooms": "森林里有蘑菇",
    "the gods will be pleased": "众神会很高兴",
    "the grass is greener on the other side": "那边的草更绿",
    "the great outdoors beckons": "伟大的户外活动在召唤",
    "the land of the free": "自由之地",
    "the perks of power": "权力的好处",
    "the return is guaranteed": "回报有保证",
    "Therapy": "治疗",
    "there is a crack in everything, that's how the light gets in.": "万物皆有裂痕，那是光线进来的地方。",
    "these royalties are insane!": "这些版税太疯狂了！",
    "they are watching": "他们在看",
    "they can print unlimited of the stuff..": "他们可以打印无限的东西..",
    "they deserve this": "他们应得的",
    "they have insurance against this anyhow": "无论如何他们都有保险",
    "they love me": "他们爱我",
    "they ROCKED!": "他们震撼了！",
    "think like me": "像我一样思考",
    "This fucking guy!": "这个该死的家伙！",
    "this is hard work..": "这很辛苦..",
    "this is me now": "这就是现在的我",
    "This. is. Africa.": "这。 是。 非洲。",
    "time to grow up, welcome to the real world kid": "是时候长大了，欢迎来到现实世界的孩子",
    "Time to pick your carrots!": "是时候摘胡萝卜了！",
    "to be rich": "变得富有",
    "to infinity": "到无限",
    "today shall be a holiday": "今天是假期",
    "tomato? potato!": "番茄？ 土豆！",
    "tomorrow I sleep": "明天我睡觉",
    "top of the line": "线的顶部",
    "Travel Bug": "旅行虫",
    "Trigger an Awkward Social Movement": "引发尴尬的社会运动",
    "true love only comes once": "真爱只有一次",
    "truly a masterpiece!": "真正的杰作！",
    "twice as happy": "双倍快乐",
    "UCFE": "UCFE",
    "unlike those poor kids": "不像那些可怜的孩子",
    "Unlimited Energy!": "无限能量！",
    "Unlocked in Full Version": "完整版解锁",
    "Volunteer at a Soup Kitchen": "在施粥所做志愿者",
    "volunteers needed": "需要志愿者",
    "wanna buy this globe light?": "想买这个地球灯吗？",
    "wanna fight": "想打架",
    "Warehouse Work": "仓库工作",
    "wasn't me": "不是我",
    "we don't need no water": "我们不需要水",
    "Wealthy Man Investment Plan": "富翁投资计划",
    "wear it everywhere I go": "无论我走到哪里都戴着它",
    "Welcome to Idle Trillionaire. Earn Money, Be Happy.": "欢迎来到《闲置亿万富翁》。 赚钱，快乐。",
    "welcome to the club": "欢迎来到俱乐部",
    "what a view": "多么美妙的风景",
    "what a weight off": "体重减轻了多少",
    "what amazing memories": "多么美好的回忆",
    "what can we buy next honey?": "亲爱的，接下来我们可以买什么？",
    "what does it say?": "它说什么？",
    "what doesn't kill you makes you stronger": "那些杀不死你的都会让你变得更强大",
    "what goes up must come down": "有升必有降",
    "where is Master Splinter": "斯普林特大师在哪里",
    "Win a Gold Medal in the Olympics": "在奥运会上赢得金牌",
    "Win a Million Dollars!": "赢取百万美元！",
    "Win a Pie Eating Contest": "赢得吃馅饼比赛",
    "Win a Street Fight": "赢得街头斗殴",
    "Win an All Inclusive Safari": "赢得全包游猎之旅",
    "Win the Slot Machine Jackpot": "赢得老虎机大奖",
    "Win the Yacht Racing Championships": "赢得游艇竞赛锦标赛",
    "wise words from the rich to the rich": "富人对富人的至理名言",
    "with glass walls": "有玻璃墙",
    "with guns": "带枪",
    "Woof woof!": "汪汪！",
    "Work / Work Balance": "工作/工作平衡",
    "worth every penny": "值得每一分钱",
    "Write a Hit Movie": "写一部热门电影",
    "years /": "年 /",
    "Yoga Lesson": "瑜伽课",
    "you are welcome": "不客气",
    "You can now tango like a pro!": "您现在可以像专业人士一样探戈！",
    "You found a great tenant!": "你找到了一个很棒的租客！",
    "you guys know any whales?": "你们认识鲸鱼吗？",
    "you have passed the test, you will be rewarded handsomely": "你通过了考验，你将获得丰厚的奖励",
    "You Know You're Rich When You're Buying This": "当你买这个的时候你就知道你很有钱了",
    "you learned how to make sushi!": "你学会了如何做寿司！",
    "you never saw nothing": "你什么也没看见",
    "you work hard for your money": "你为你的钱而努力工作",
    "Your Goal is to Earn a Trillion or More Dollars": "您的目标是赚取一万亿或更多美元",
    "Your house is so clean now!": "你家现在真干净啊！",
    "your income can grow only to the extent that you do": "你的收入只能在你做的范围内增长",
    "yum": "嗯",
    "180 billion each": "各1800亿",
    "8 billion folks, 8 trillion bucks": "80亿人，8万亿美元",
    "90% rare metal": "90% 稀有金属",
    "A Big Play": "一场大戏",
    "a hard man to please": "很难取悦的人",
    "a huge play actually": "实际上是一场大戏",
    "A Momentary Lapse in Judgement": "判断力的短暂失误",
    "A Shady Back Alley Offer": "阴暗的后巷优惠",
    "Accept Generous Donations": "接受慷慨捐赠",
    "Act on an Insider Tip": "根据内幕消息采取行动",
    "all 'mine'": "全是我的'",
    "all profits will be mine": "所有利润都是我的",
    "An Investment Matures": "投资成熟",
    "and air condition the desert": "和空调沙漠",
    "and don't apologize": "并且不要道歉",
    "Annual Bonus = $1,000": "年度奖金 = $1,000",
    "another 200 trillion more to go...": "还有 200 万亿美元还剩 200 万亿美元……",
    "are you listening to me?": "你在听我说吗？",
    "Become a Tyrant": "成为暴君",
    "Become Blind with Cruelty and Greed": "因残忍和贪婪而变得盲目",
    "become dictator": "成为独裁者",
    "Become Insane with Malice and Psychosis": "因恶意和精神病而变得疯狂",
    "Become Mad with Evil and Corruption": "因邪恶和腐败而疯狂",
    "Big Boys Club": "大男孩俱乐部",
    "bow to me": "向我鞠躬",
    "bravo": "布拉沃",
    "Break the Guinness World Record for Longest Hoola Hoop Session": "打破最长呼啦圈吉尼斯世界纪录",
    "Bribe the Government": "贿赂政府",
    "bring back the Burmese way of life, belief system, and traditions": "带回缅甸的生活方式、信仰体系和传统",
    "but at what cost? and from whom?": "但代价是什么？ 来自谁？",
    "Buy 20 Million Houses": "买2000万栋房子",
    "Buy 600,000 Acres of Untouched Land": "购买 600,000 英亩未开发土地",
    "Buy a 10 Million Dollar 'Beater'": "购买价值 1000 万美元的“击球手”",
    "Buy a High-End Yacht": "购买高端游艇",
    "Buy a Historical Castle from England": "从英国购买一座历史城堡",
    "Buy a Super Expensive Outfit": "买一套超级昂贵的衣服",
    "Buy America": "买美国货",
    "Buy an E-commerce Giant": "收购电商巨头",
    "Buy an Island": "买一座岛",
    "Buy Australia": "购买澳大利亚",
    "Buy Barbados": "购买巴巴多斯",
    "Buy Bolivia": "购买玻利维亚",
    "Buy Brazil": "购买巴西",
    "Buy Canada": "购买加拿大",
    "Buy China": "购买中国",
    "Buy Colombia": "购买哥伦比亚",
    "Buy Costa Rica": "购买哥斯达黎加",
    "Buy Egypt": "购买埃及",
    "Buy Elon Husk and Jeff Bozos": "购买埃隆·赫斯克和杰夫·博佐斯",
    "Buy Finland": "购买芬兰",
    "Buy France": "购买法国",
    "Buy Germany": "购买德国",
    "Buy Greece": "购买希腊",
    "Buy Hong Kong": "购买香港",
    "Buy Hungary": "购买匈牙利",
    "Buy India": "购买印度",
    "Buy Jamaica": "购买牙买加",
    "Buy Japan": "购买日本",
    "Buy Kazakhstan": "购买哈萨克斯坦",
    "Buy Kenya": "购买肯尼亚",
    "Buy Mexico": "购买墨西哥",
    "Buy Morocco": "购买摩洛哥",
    "Buy Myanmar": "购买缅甸",
    "Buy New Zealand": "购买新西兰",
    "Buy Norway": "购买挪威",
    "Buy Out a Hedge Fund": "买断对冲基金",
    "Buy Panama": "购买巴拿马",
    "Buy Papua New Guinea": "购买巴布亚新几内亚",
    "Buy Poland": "购买波兰",
    "Buy Portugal": "购买葡萄牙",
    "Buy Rwanda": "购买卢旺达",
    "Buy Saudi Arabia": "购买沙特阿拉伯",
    "Buy South Korea": "购买韩国",
    "Buy Sri Lanka": "购买斯里兰卡",
    "Buy Sweden": "购买瑞典",
    "Buy Switzerland": "购买瑞士",
    "Buy The Bahamas": "购买巴哈马",
    "Buy the Entire Slum.": "买下整个贫民窟。",
    "Buy the Internet": "购买互联网",
    "Buy the United Kingdom": "购买英国",
    "Buy this junk!": "买这个垃圾！",
    "Buy Turkey": "购买土耳其",
    "Buy Ukraine": "购买乌克兰",
    "Buy Vietnam": "购买越南",
    "Buy Zimbabwe": "购买津巴布韦",
    "cards are unlocked by other cards": "卡被其他卡解锁",
    "Cash in a Bug Bounty": "漏洞赏金现金",
    "Colonize the Moon": "殖民月球",
    "congratulations on your accomplishments": "祝贺你取得的成就",
    "Construct a Global Hotel Chain": "打造全球连锁酒店",
    "Create 100 New Billionaires": "创造 100 位新亿万富翁",
    "Create a Niche Market for Yellow Snow": "为黄雪创造利基市场",
    "Cry Salty Tears on Your Money Pile": "在你的钱堆上流下咸咸的眼泪",
    "Cut an Expensive Habit": "戒掉昂贵的习惯",
    "democracy does not apply to the rich": "民主不适用于富人",
    "Design and Market a Glove for the Six-Fingered Folk": "为六指族设计和销售手套",
    "Develop Algorithm": "开发算法",
    "dis my hood!!": "这是我的引擎盖！",
    "Discover a Large Diamond Deposit": "发现大型钻石矿床",
    "Discover the Cure for a World Pandemic": "探索世界流行病的治疗方法",
    "Donate A Billion": "捐赠十亿",
    "Donate Half a Million to a Cause": "为一项事业捐赠五十万",
    "easy money": "快钱",
    "Embarrass Yourself in Public": "在公共场合让自己难堪",
    "Enter the Import Export Business": "进入进出口业务",
    "Establish an Orbital Corporation": "建立轨道公司",
    "every one is so attractive": "每一个都那么吸引人",
    "everyone is talkin' bout it": "每个人都在谈论它",
    "fiesta and party like there's no mañana": "嘉年华和派对就像没有马纳纳一样",
    "Find a Four Leaf Clover": "找到四叶草",
    "Find a Glass Eyeball and Return it to its Rightful Owner": "找到玻璃眼球并将其归还给其合法所有者",
    "Find a Lion and a Witch in your Wardrobe": "在你的衣柜里找到狮子和女巫",
    "Find a Precious Artifact and Open a Tourist Attraction": "找到一件珍贵的文物并打开一个旅游景点",
    "Flip a Vacation Mansion": "翻转度假别墅",
    "Follow a Rainbow and Find a Massive Pot of Gold at the End": "跟随彩虹，最终找到一大罐金子",
    "Follow a Rainbow and Find a Very Small Pot of Gold at the End": "跟随彩虹，最终找到一小罐金子",
    "for 400 trillion the worlds wealth is yours": "400万亿世界财富都是你的",
    "for the 1%": "对于那1%",
    "for the schnitzel": "对于炸肉排",
    "for the skiing...": "对于滑雪...",
    "for the whales": "对于鲸鱼",
    "free bananas for everyone": "为所有人提供免费香蕉",
    "Fund a Massive Clean the Ocean Campaign": "资助大规模清洁海洋运动",
    "Fund Aliens": "基金外国人",
    "Get Carried thru the Jungle on a Sedan Chair": "乘坐轿子穿越丛林",
    "Get into a Dumpster Brawl": "卷入垃圾箱斗殴",
    "Get Knighted, Command Respect": "获得爵位，赢得尊重",
    "Get on the Board for Blackrock": "加入贝莱德董事会",
    "Give Everyone on Earth One Thousand Dollars": "给地球上的每个人一千美元",
    "Give in to a Serious Craving for Turducken": "屈服于对火鸡的强烈渴望",
    "give us more, few hundred billion have you, merely a tiny fraction appended": "给我们更多，你有几千亿，只是附加一小部分",
    "Global Domination": "全球统治",
    "gobble quack cluck yum": "狼吞虎咽嘎嘎咯咯百胜",
    "guess I'm going to fade into Bolivian": "我想我会逐渐融入玻利维亚语",
    "hakuna matata": "哈库纳马塔塔",
    "here I am law": "我是法律",
    "Hire a Full Time World Class Personal Masseuse": "聘请全职世界级私人按摩师",
    "Host a Spectacle All Will Pay to See": "举办一场所有人都愿意付费观看的盛会",
    "how can anyone be this happy": "怎么会有人这么幸福",
    "How do you get a one-armed Polish fellow out of a tree?": "如何把一个独臂波兰人从树上救下来？",
    "I ..die human... NEED MORE ..die..MONEY": "我..死了人类...需要更多..死..钱",
    "I can not eat another bite": "我不能再吃一口",
    "I can't believe this offer!?": "我简直不敢相信这个优惠！？",
    "I could have ruined them": "我本可以毁了他们",
    "I desired their GDP as personal income": "我希望他们的 GDP 作为个人收入",
    "I fly often, and when I do, It's in luxury": "我经常坐飞机，当我坐飞机时，一切都是奢侈的",
    "I just love the landscape": "我只是喜欢风景",
    "I know you came from over seas, but were full until winter": "我知道你来自海外，但直到冬天都吃饱了",
    "I like variety": "我喜欢多样性",
    "I look good": "我看起来很好",
    "I lost myself that day...": "那天我迷失了自己...",
    "I love Mr. Lanka": "我爱兰卡先生",
    "I made my own luck": "我的运气是我自己创造的",
    "I might move into a pyramid": "我可能会搬进金字塔",
    "I need your stuff you broke peasants": "我需要你的东西，你破坏了农民",
    "I only my first one": "我只有我的第一个",
    "I see you": "我看见你",
    "I will change all your lives! But you owe me..": "我会改变你们所有人的生活！ 但你欠我的..",
    "I will right the injustice here": "我会纠正这里的不公正",
    "I.... I... just... I": "我……我……只是……我",
    "I'll start a colony": "我将开始一个殖民地",
    "I'm on a boat!": "我在船上！",
    "if money can buy happiness, happiness can buy money": "如果金钱可以买到幸福，那么幸福也可以买到金钱",
    "improve dental care": "改善牙齿护理",
    "Intangible Happiness": "无形的幸福",
    "is that a stingray mate?": "那是黄貂鱼伴侣吗？",
    "Issue Stimulus Cheques": "发放刺激支票",
    "it is for a good cause, more sacrifice": "这是为了一个好的事业，更多的牺牲",
    "it is hard to conceive how huge this is..": "很难想象这是有多大..",
    "it is rightfully mine!": "它理应是我的！",
    "it served neither me nor my wealth and greed": "它既不利于我，也不利于我的财富和贪婪",
    "it trades meme stocks based on Reddit trends": "它根据 Reddit 趋势交易 meme 股票",
    "it's a take it or leave it deal bud": "这是一个要么接受要么放弃的交易芽",
    "It’s getting hot in here....": "这里越来越热了......",
    "it's just my shitty thrasher car": "这只是我的破鸫车",
    "itching for fame!": "渴望名利！",
    "jag älskar dig": "杰格·阿尔斯卡挖掘",
    "jah man": "贾曼",
    "jeepers, creepers, where’d you get those peepers?": "吉普车、爬行者，你从哪里得到这些窥视器的？",
    "just a drop in the bucket, in my pocket now": "只是沧海一粟，现在在我的口袋里",
    "just call me Shakira": "就叫我夏奇拉吧",
    "just need to wait now..": "现在只需要等待..",
    "Launch a Spy Satellite Network": "启动间谍卫星网络",
    "learn the way of the samurai": "学习武士之道",
    "let's go up that hill please, quickly now!": "我们快点上那座山吧！",
    "Liquidate 10% of Blackrock": "清算 10% 的贝莱德",
    "Liquidate 90% of Blackrock": "清算贝莱德 90% 的股份",
    "Lose all Compassion for the Human Race": "失去对人类的所有同情心",
    "Major Turn of Fortune": "命运的重大转变",
    "majority stake holder here": "多数股东在这里",
    "Make an Adult Film": "制作成人电影",
    "Make your Father Proud": "让你的父亲感到骄傲",
    "Mass Produce Affordable Clean Electric Cars": "批量生产经济实惠的清洁电动汽车",
    "military not included": "不包括军事",
    "Mine an Asteroid": "开采小行星",
    "money money...stupid.. human.. MONEY MONEY": "钱钱...愚蠢..人类..钱钱",
    "my own little paradise": "我自己的小天堂",
    "my precious": "我的宝贝",
    "need a wax job?": "需要打蜡吗？",
    "need more money": "需要更多钱",
    "need MORE MONEY...grrr": "需要更多钱...grrr",
    "needed to be done": "需要做",
    "never say I regret, always say I learned": "永远不要说我后悔，总是说我学会了",
    "Never Sleep - Only Profit": "永不睡觉——只有利润",
    "no cash gained": "没有获得现金",
    "no happy gained": "没有获得快乐",
    "No Reward, No Punishment, You Have the Money.... You Want This Card To Turn Yellow": "没有奖励，没有惩罚，你有钱......你想让这张卡变成黄色",
    "Nobel Prize": "诺贝尔奖",
    "now they see it my way": "现在他们以我的方式看待它",
    "officially the Republic of Türkiye": "正式名称为土耳其共和国",
    "oh my lucky stars!": "哦，我的幸运星！",
    "oh the data...": "哦数据...",
    "only the first of many": "只是众多中的第一个",
    "Open Gift": "打开礼物",
    "Own 50% of Global Wealth": "拥有全球50%的财富",
    "Partner With a Kardashev III Intelligence Level AI": "与卡尔达肖夫 III 级人工智能合作",
    "Pave All Roads Solid Gold": "铺平所有道路纯金",
    "Pay Off that Nasty Credit Card": "还清那张讨厌的信用卡",
    "Pho every day boyz!!!": "每天河粉男孩！",
    "post a link on social media": "在社交媒体上发布链接",
    "Predatory Take Over of an Obscure Country": "掠夺性接管一个默默无闻的国家",
    "Purchase a Military": "购买军队",
    "pure greed": "纯粹的贪婪",
    "qui vivra verra": "基维维拉维拉",
    "quick 5 million": "快500万",
    "rename Earth after yourself": "以你自己的名字重新命名地球",
    "Rig an Election": "操纵选举",
    "Rob Someone to Feel Alive": "抢劫某人来感觉自己还活着",
    "rock out in your rocking chair": "坐在摇椅上摇摆",
    "sadly it did not make me feel more human": "遗憾的是它并没有让我感觉更人性化",
    "saving the hippos, rhinos and birdlife": "拯救河马、犀牛和鸟类",
    "scum bag got what he deserved": "渣男得到了他应得的",
    "see, I care": "瞧，我关心",
    "Sell your Bitcoin": "卖掉你的比特币",
    "Sell Your Soul to the Devil": "将你的灵魂出卖给魔鬼",
    "serves you right": "为你服务是对的",
    "Spike Grandma’s Punch with Gin": "斯派克奶奶的杜松子潘趣酒",
    "Stab Your Business Partner in the Back": "在背后捅你的商业伙伴一刀",
    "Star in a Hit Movie": "主演热门电影",
    "steal back the gold": "偷回黄金",
    "Steal from the Less Rich": "从不那么富有的人那里偷东西",
    "Swindle away Ownership of a Criminal Law Conglomerate": "骗取刑法集团的所有权",
    "Take a Really Long Walk Off a Really Short Pier": "从很短的码头走很长一段路",
    "Take Your Flea Circus to Hollywood": "把你的跳蚤马戏团带到好莱坞",
    "the air of Portugal has a natural happiness in it": "葡萄牙的空气里有一种天然的快乐",
    "the canal is now private property.. sorry. Go AROUND!": "运河现在是私有财产..抱歉。 四处走走！",
    "the fingers have been in everything for too long!": "手指已经在一切事物中呆得太久了！",
    "the fjords, mountains and northern lights - all mine": "峡湾、山脉和北极光——都是我的",
    "the land of vibrant traditions and technological wonders": "这片充满活力的传统和技术奇迹的土地",
    "The Most Expensive Wedding EVER": "有史以来最昂贵的婚礼",
    "the pinnacle of aristocratic success": "贵族成功的顶峰",
    "the traditional tribal villages will thrive under me": "传统部落村庄将在我的领导下蓬勃发展",
    "they call it mellow yellow": "他们称之为柔和的黄色",
    "thousands of islands and all of them mine": "数千个岛屿，全都是我的",
    "Time a Market Crash": "把握市场崩盘时机",
    "told you so": "告诉过你了",
    "toss out that mask!": "扔掉那个面具！",
    "totally not worth it": "完全不值得",
    "totally worth it": "完全值得的",
    "Trillion Dollar Sacrifice": "万亿美元的牺牲",
    "Try Human": "尝试人类",
    "Value Money Over Life Itself": "重视金钱胜过生命本身",
    "very nice": "很不错",
    "Was it worth it?": "它值得吗？",
    "we are good people, right?": "我们都是好人，对吧？",
    "we can finally go snowboarding": "我们终于可以去滑雪了",
    "we need more printers": "我们需要更多打印机",
    "we will mine the Moon": "我们将开采月球",
    "we will rebuild!": "我们将重建！",
    "Welcome Back.": "欢迎回来。",
    "what else is in here?": "这里还有什么？",
    "while drunk": "醉酒时",
    "Win an Oscar": "赢得奥斯卡奖",
    "Win the Academy Awards": "赢得奥斯卡金像奖",
    "World Tour with Luxury Private Airline": "豪华私人航空公司环游世界",
    "Write a Program that Generates Passive Income": "编写一个产生被动收入的程序",
    "x = Ω(f(n))": "x = Ω(f(n))",
    "yeah, we can move it": "是的，我们可以移动它",
    "you are famous now": "你现在出名了",
    "you can leave Hong Kong, but it will never leave you": "你可以离开香港，但香港永远不会离开你",
    "you should see the other guy....": "你应该去看看另一个人......",
    "you should see the ring": "你应该看到戒指",
    "You were away for:": "您离开了：",
    "You were out of focus for:": "您因以下原因而无法集中注意力：",
    "you will follow my commands": "你会听从我的命令",
    "you're smokin moon rocks bro": "你在抽烟，兄弟",
    "your first billion!": "你的第一个十亿！",
    "Your Start Up is Bought Out": "你的初创公司被收购了",
    "yum....": "嗯……",
    " chance to instantly win 💰 or 😄.": "有机会立即赢得💰或😄。",
    " Toggle view modes.": "切换视图模式。",
    "- Compare your 'Milestones' with other players.": "- 将您的“里程碑”与其他玩家进行比较。",
    "- Earn a trillion 💰 dollars or beyond.": "- 赚取一万亿美元或更多。",
    "- Privacy Policy -": "- 隐私政策 -",
    "- spend (happy 😄) and (cash 💰) to buy cards that increase the rate you earn.": "- 花费（快乐😄）和（现金💰）购买卡片，以提高您的赚取率。",
    "- You lose if 💰 drops below -$100,000.": "- 如果 💰 跌破 -$100,000，您就输了。",
    "- You lose if 😄 drops below -10,000.": "- 如果 😄 跌至 -10,000 以下，您就输了。",
    "(demo)": "（演示）",
    "#sideHustle": "#sideHustle",
    "1. paste your": "1.粘贴你的",
    "2. click": "2.点击",
    "a$$ #*%@": "$$ #*%@",
    "About": "关于",
    "All Games": "所有游戏",
    "cards of the full game. The full game is paid and unlocks and additional": "完整游戏的卡牌。 完整游戏已付费并解锁和额外",
    "cards. You will be able to transfer your progress over from the Demo.": "牌。 您将能够从演示转移您的进度。",
    "Close": "关闭",
    "Copy Save String": "复制保存字符串",
    "Event History": "历史事件",
    "GOAL": "目标",
    "Hints": "提示",
    "How to Play": "玩法",
    "Idle Influencer": "闲置影响者",
    "in the text box": "在文本框中",
    "Join the Discord": "加入 Discord",
    "Links": "链接",
    "Load Game File": "加载游戏文件",
    "Load Save String": "加载保存字符串",
    "Main Menu": "主菜单",
    "New Game": "新游戏",
    "Other Games": "其他游戏",
    "RESET Progress": "重置进度",
    "Save Game File": "保存游戏文件",
    "SAVE STRING": "保存字符串",
    "Show": "显示",
    "The Slanted Room (developer)": "倾斜的房间（开发商）",
    "This Demo includes the first": "该演示包括第一个",
    "To load a game": "加载游戏",
    "Warning - this will permanently delete your save file": "警告 - 这将永久删除您的保存文件",
    "✅ Buy a Bike": "✅ 买一辆自行车",
    "✅ First Kiss": "✅初吻",
    "✅ Live thru 1 year": "✅ 存活1年",
    "✅ Live thru a day": "✅ 度过一天",
    "✅ Live thru a month": "✅ 活过一个月",
    "✅ Live thru a Week": "✅ 活过一周",
    "🏆 Your First Trillion! You Win 💰": "🏆 你的第一个万亿！ 你赢了💰",
    "Annual Bonus = $2,000": "年度奖金 = $2,000",
    "Become a Billionaire 💰": "成为亿万富翁💰",
    "Become a Millionaire 💰": "成为百万富翁💰",
    "Break your Neck in a Bike Accident": "在自行车事故中摔断脖子",
    "Find a Coin on the Ground": "找到地上的硬币",
    "Find a Dollar": "寻找美元",
    "Go to Movies": "去看电影",
    "Goals": "目标",
    "I thought I was E.T. until I hit the ground": "我以为我是E.T. 直到我落地",
    "it is rare, worth a fortune": "很稀有，价值不菲",
    "my lucky day": "我的幸运日",
    "Part Time Job": "兼职工作",
    "pays ok, I guess": "我想支付还可以",
    "popcorn?": "爆米花？",
    "Reach the milestones in as few days as possible": "在尽可能短的时间内达到里程碑",
    "Try Again": "再试一次",
    "Win the Lottery": "中彩票",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\+([\d\.,]+)😄$/,
    /^\-([\d\.,]+)😄$/,
    /^\-\$([\d\.,]+)😄$/,
    /^\+([\d\.,]+)💰$/,
    /^\+\$([\d\.,]+)💰$/,
    /^\-([\d\.,]+)💰$/,
    /^\-\$([\d\.,]+)💰$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Live thru (.+) years$/, '生存超过 $1 年'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Happy 😄: ([\d\.,]+).$/, '快乐 😄: $1.'],
    [/^([\d\.,]+) years \/ ([\d\.,]+) days$/, '$1 年 \/ $2 天'],
    [/^([\d\.,]+) year \/ ([\d\.,]+) days$/, '$1 年 \/ $2 天'],
    [/^([\d\.,]+) days \/ ([\d\.,]+) hours$/, '$1 天 \/ $2 小时'],
    [/^([\d\.,]+) minutes \/ ([\d\.,]+) seconds$/, '$1 分钟 \/ $2 秒'],
    [/^💰x ([\d\.,]+) hours$/, '💰x $1 小时'],
    [/^😄x ([\d\.,]+) days$/, '😄x $1 天'],
    [/^\+([\d\.,]+)😄\/ day$/, '\+$1😄\/ 天'],
    [/^\+([\d\.,]+) 😄\/ day$/, '\+$1 😄\/ 天'],
    [/^\+([\d\.,]+) 😄 \/ day.$/, '\+$1 😄 \/ 天。'],
    [/^\-([\d\.,]+)😄\/ day$/, '\-$1😄\/ 天'],
    [/^\$([\d\.,]+) \/ hour$/, '\$ $1 \/ 小时'],
    [/^\+\$([\d\.,]+)💰\/ hour$/, '\+\$ $1💰\/ 小时'],
    [/^\-\$([\d\.,]+)💰\/ hour$/, '\-\$ $1💰\/ 小时'],
    [/^\+\$([\d\.,]+)💰 annually$/, '\+\$ $1💰 每年'],
    [/^\-\$([\d\.,]+)💰 annually$/, '\-\$ $1💰 每年'],
    [/^\+\$([\d\.,]+)💰cost of living$/, '\+\$ $1💰 生活成本'],
    [/^\-\$([\d\.,]+)💰cost of living$/, '\-\$ $1💰 生活成本'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);